// Farm animals and their coop: chickens and ducks (3 facings x 2 walk frames; left mirrors right),
// eggs, the coop building, the hay hopper and a straw nest.
import { grid, set, fillRect, ellipse, outline, parse, polygon } from './raster.js';
import { hashf } from '../core/rng.js';

const hline = (g, x0, x1, y, c) => { for (let x = x0; x <= x1; x++) set(g, x, y, c); };

// Keys: o outline, W body, w body shade, H head, r comb, g beak, e eye, y legs.
const CHICKEN = {
  right: [`
    ................
    .........rr.....
    ........rrro....
    ........oWWo....
    .......oWeWgg...
    .......oWWWo....
    ..o....oWWWo....
    .oWo..oWWWWo....
    .oWWooWWWWWo....
    .oWWWWWWWWwo....
    ..oWWWWWWwwo....
    ..oWWWWWwwo.....
    ...ooWWwwo......
    .....oooo.......
    .....y.y........
    ....yy.yy.......`, `
    ................
    .........rr.....
    ........rrro....
    ........oWWo....
    .......oWeWgg...
    .......oWWWo....
    ..o....oWWWo....
    .oWo..oWWWWo....
    .oWWooWWWWWo....
    .oWWWWWWWWwo....
    ..oWWWWWWwwo....
    ..oWWWWWwwo.....
    ...ooWWwwo......
    .....oooo.......
    ....y...y.......
    ...yy..yy.......`],
  down: [`
    ................
    .......rr.......
    ......rrro......
    ......oWWo......
    .....oWWWWo.....
    .....eWggWe.....
    .....oWggWo.....
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...oWWWWWWwwo...
    ....oWWWWwwo....
    .....oooooo.....
    ......y..y......
    ......y..y......
    .....yy..yy.....`, `
    ................
    .......rr.......
    ......rrro......
    ......oWWo......
    .....oWWWWo.....
    .....eWggWe.....
    .....oWggWo.....
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...oWWWWWWwwo...
    ....oWWWWwwo....
    .....oooooo.....
    ......y..y......
    .....yy...y.....
    ..........yy....`],
  up: [`
    ................
    .......rr.......
    ......rrro......
    ......oWWo......
    .....oWWWWo.....
    .....oWWWWo.....
    ......oWWo......
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...oWWWoWWwwo...
    ....oWWoWwwo....
    .....oooooo.....
    ......y..y......
    ......y..y......
    .....yy..yy.....`, `
    ................
    .......rr.......
    ......rrro......
    ......oWWo......
    .....oWWWWo.....
    .....oWWWWo.....
    ......oWWo......
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...oWWWoWWwwo...
    ....oWWoWwwo....
    .....oooooo.....
    ......y..y......
    .....yy...y.....
    ..........yy....`],
};

// Ducks: a green head, a long flat bill, a brown-grey body.
const DUCK = {
  right: [`
    ................
    ................
    ........oo......
    .......oHHo.....
    .......oHeHggg..
    .......oHHHo....
    ........oHo.....
    .oo....oWWo.....
    .oWoooWWWWWo....
    .oWWWWWWWWwo....
    ..oWWWWWWwwo....
    ..owWWWWwwo.....
    ...oowwwwo......
    .....oooo.......
    .....gg.gg......
    ................`, `
    ................
    ................
    ........oo......
    .......oHHo.....
    .......oHeHggg..
    .......oHHHo....
    ........oHo.....
    .oo....oWWo.....
    .oWoooWWWWWo....
    .oWWWWWWWWwo....
    ..oWWWWWWwwo....
    ..owWWWWwwo.....
    ...oowwwwo......
    .....oooo.......
    ....gg...gg.....
    ................`],
  down: [`
    ................
    ................
    ......oooo......
    .....oHHHHo.....
    .....eHHHHe.....
    .....oHggHo.....
    ......oggo......
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...owWWWWWwwo...
    ....owWWWwwo....
    .....oooooo.....
    ......g..g......
    .....gg..gg.....
    ................`, `
    ................
    ................
    ......oooo......
    .....oHHHHo.....
    .....eHHHHe.....
    .....oHggHo.....
    ......oggo......
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...owWWWWWwwo...
    ....owWWWwwo....
    .....oooooo.....
    .....gg...g.....
    ..........gg....
    ................`],
  up: [`
    ................
    ................
    ......oooo......
    .....oHHHHo.....
    .....oHHHHo.....
    .....oHHHHo.....
    ......oHHo......
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...owWWoWWwwo...
    ....owWowwwo....
    .....oooooo.....
    ......g..g......
    .....gg..gg.....
    ................`, `
    ................
    ................
    ......oooo......
    .....oHHHHo.....
    .....oHHHHo.....
    .....oHHHHo.....
    ......oHHo......
    ....ooWWWWoo....
    ...oWWWWWWWWo...
    ...oWWWWWWWwo...
    ...owWWoWWwwo...
    ....owWowwwo....
    .....oooooo.....
    .....gg...g.....
    ..........gg....
    ................`],
};

const LEGENDS = {
  chicken: { o: 'ink3', W: 'ink6', w: 'ink5', r: 'red2', g: 'gold2', e: 'ink0', y: 'gold1' },
  duck: { o: 'wood0', W: 'stone3', w: 'stone2', H: 'grass2', g: 'gold1', e: 'ink0' },
};

/** Frames as { name: grid }: `${kind}_${dir}_${i}`. */
export function animalFrames() {
  const out = {};
  for (const [kind, set0] of [['chicken', CHICKEN], ['duck', DUCK]]) {
    for (const [dir, frames] of Object.entries(set0)) frames.forEach((rows, i) => { out[`${kind}_${dir}_${i}`] = parse(rows, LEGENDS[kind]); });
  }
  return out;
}

export function eggIcons() {
  const egg = (shell, shade, light) => {
    const g = grid(16, 16);
    ellipse(g, 8, 9, 4.5, 5.5, shade);
    ellipse(g, 7, 8, 3.5, 4.5, shell);
    set(g, 6, 6, light); set(g, 6, 7, light);
    return outline(g, { color: 'wood1', pad: 0 });
  };
  return { egg: egg('straw4', 'straw3', 'ink6'), duck_egg: egg('water4', 'stone4', 'ink6') };
}

/** The coop: plank walls under a small thatch roof, a hatch with a ramp, a wire window. 84x58. */
export function coopBuilding() {
  const W = 84, H = 58;
  const g = grid(W, H);
  fillRect(g, 6, 24, 72, 30, 'wood2');
  for (let y = 24; y < 54; y += 4) hline(g, 6, 77, y, 'wood1');
  for (const x of [6, 30, 52, 74]) { fillRect(g, x, 24, 3, 30, 'wood1'); set(g, x, 24, 'wood3'); }
  // Wire window.
  fillRect(g, 12, 30, 14, 10, 'ink1');
  for (let x = 12; x < 26; x += 3) for (let y = 30; y < 40; y += 3) set(g, x + (y % 2), y, 'stone3');
  // Hatch (centred on the door tile) and ramp; a second wire window on the right.
  fillRect(g, 36, 36, 14, 18, 'wood0');
  fillRect(g, 37, 37, 12, 16, 'wood1');
  polygon(g, [[34, 57], [38, 52], [48, 52], [52, 57]], 'wood3');
  for (let x = 37; x < 50; x += 3) set(g, x, 55, 'wood1');
  fillRect(g, 56, 30, 14, 10, 'ink1');
  for (let x = 56; x < 70; x += 3) for (let y = 30; y < 40; y += 3) set(g, x + (y % 2), y, 'stone3');
  // Thatch roof.
  polygon(g, [[0, 28], [12, 6], [72, 6], [84, 28]], 'straw2');
  for (let y = 6; y < 28; y++) for (let x = 0; x < W; x++) {
    if (!(y >= 6 && x >= 12 - (y - 6) * 0.55 && x <= 72 + (y - 6) * 0.55)) continue;
    const s = hashf(x, Math.floor(y / 3), 5, 1);
    set(g, x, y, x < 42 ? (s > 0.75 ? 'straw4' : 'straw3') : (s > 0.8 ? 'straw3' : 'straw2'));
  }
  hline(g, 0, 83, 28, 'straw0');
  hline(g, 1, 82, 27, 'straw1');
  fillRect(g, 12, 3, 60, 4, 'wood1');
  hline(g, 12, 71, 3, 'wood3');
  return outline(g, { color: 'wood0' });
}

/** Hay hopper against the coop wall, hay showing at the top. 16x26. */
export function hopper() {
  const g = grid(16, 26);
  fillRect(g, 1, 4, 14, 22, 'wood3');
  for (let y = 8; y < 26; y += 6) hline(g, 1, 14, y, 'wood2');
  fillRect(g, 3, 1, 10, 4, 'straw3');
  for (const x of [4, 7, 10]) set(g, x, 0, 'straw4');
  fillRect(g, 4, 20, 8, 4, 'wood1');
  return outline(g, { color: 'wood0' });
}

/** A straw nest on the coop floor. 16x9. */
export function nest() {
  const g = grid(16, 9);
  ellipse(g, 8, 5, 7, 3.5, 'straw2');
  ellipse(g, 8, 4, 5, 2, 'straw1');
  for (const x of [2, 5, 9, 13]) set(g, x, 6, 'straw3');
  return outline(g, { color: 'straw0' });
}
