// Crop growth-stage sprites, 16x20, anchored at the bottom centre (8, 20) of the soil tile.
// Stage 0 = seeds, 1 = sprout, 2 = young, 3 = mature, 4 = ripe (harvestable).
import { parse } from './raster.js';

const L = {
  o: 'grass0', d: 'grass1', m: 'grass2', l: 'grass3', L: 'grass4', h: 'grass5', H: 'grass6',
  k: 'straw4', K: 'wood0', w: 'ink6', W: 'ink5', V: 'ink4',
  r: 'red2', R: 'red1', s: 'red4', y: 'gold2', f: 'ink6', F: 'ink5',
  p: 'grass4', P: 'grass2', t: 'teal1', T: 'teal0',
};

const SEEDS = `
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ....KK....KK....
  ...KkkK..KkkK...
  ....KK.KK.KK....
  ......KkkK......
  .......KK.......`;

const SPROUT = `
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  .....oo...oo....
  ....oHho.ohHo...
  ....olhLoLhlo...
  .....oolLloo....
  .......oLo......
  .......oLo......
  .......omo......
  ........o.......`;

export const CROP_ART = {
  daikon: [SEEDS, SPROUT, `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ....oo....oo....
    ...oHho..ohHo...
    ...oLhLooLhLo...
    ..oLLhlLoLhlLo..
    ..olLlhloLhlLo..
    ...ooLlLLlLoo...
    ....oolLLloo....
    ......olLlo.....
    ......oLLlo.....
    .......omo......
    ........o.......`, `
    ................
    ................
    ................
    ................
    ....oo.....oo...
    ...oHho...ohHo..
    ...oLhLo.oLhLo..
    ..oLLhlLoLLhlLo.
    ..oLhLlLoLhLllo.
    .ooLhlLlLlhLlo..
    oHhLLlLhLLlLLoo.
    oLhhLlLlhLlLLhHo
    .oLLlhLLlhLlLLlo
    ..ooLLlLLlLLloo.
    ....ooLLLLLoo...
    ......oLLlo.....
    ......oLLlo.....
    .......oLo......
    .......omo......
    ........o.......`, `
    ................
    ...oo.......oo..
    ..oHho.....ohHo.
    ..oLhLo...oLhLo.
    .oLLhlLo.oLLhlLo
    .oLhLlLooLhLllo.
    ooLhlLlLLlhLlo..
    oHhLLlLhLLlLLooo
    oLhhLlLlhLlLLhHo
    .oLLlhLLlhLlLLlo
    ..ooLLlLLlLLloo.
    ....oolLLLloo...
    .....oWwwwwWo...
    .....oWwwwwWo...
    .....oWwwwWWo...
    .....oVWwwWVo...
    ......oVWWVo....
    .......oVVo.....
    ........oo......
    ................`],
  komatsuna: [SEEDS, SPROUT, `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .....ooo.ooo....
    ....oLhLoLhLo...
    ....oLhlolhLo...
    ...ooLlLoLlLoo..
    ..oLhLllLlllhLo.
    ..olLlLLLLlLlo..
    ...oooLLLLLoo...
    ......oLLlo.....
    .......omo......
    ........o.......`, `
    ................
    ................
    ................
    ................
    ................
    ................
    .....ooo..ooo...
    ....oLhLo.oLhLo.
    ...oLhhLooLhhLo.
    ...oLhlLooLlhLo.
    ..ooLLlLooLlLLoo
    .oLhhooLLLLoohLo
    .oLhLlLlLLlLlhLo
    .olLlLlLLLLlLlLo
    ..oolLLlLLlLLoo.
    ....ooLLLLLoo...
    ......oLLLo.....
    ......oLLlo.....
    .......omo......
    ........o.......`, `
    ................
    ................
    .....ooo..ooo...
    ....oHhLo.oLhHo.
    ...oLhhLooLhhLo.
    ...oLhlLooLlhLo.
    ..oLhLlLooLlLhLo
    ..oLhLlLLLLlLhLo
    .ooLLlLlLLlLlLLo
    oHhooLLhLLLoohHo
    oLhLlLlhLlLlLhLo
    olLhLlLLLLlLhLlo
    .ooLLhLlLlLhLLoo
    ...oolLhLLLloo..
    .....ooLLLLoo...
    ......oLhLo.....
    ......oLLlo.....
    .......oLo......
    ........o.......
    ................`],
  soramame: [SEEDS, SPROUT, `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .......oo.......
    ......oHho......
    ....oooLloo.....
    ...oLhoLooLho...
    ...olLoLooLLo...
    ....ooLLloo.....
    ...oLhoLooho....
    ...oLLoLoLLo....
    ....oooLoooo....
    .......oLo......
    .......omo......
    ........o.......`, `
    ................
    ................
    ................
    .......oo.......
    ......oHho......
    ....oooLlooo....
    ...oLhoLooLho...
    ...olLoLooLLo...
    ....oooLloo.....
    ..oLhLoLooLhLo..
    ..oLLloLooLLlo..
    ...oooLLlooo....
    ..oLhoLLooLho...
    ..olLoLLooLLo...
    ...ooLLLloooo...
    ....oLhoLoLho...
    ....oooLooooo...
    .......oLo......
    .......omo......
    ........o.......`, `
    ................
    .......oo.......
    ......oHho......
    ....oooLlooo....
    ...oLhoLooLho...
    ...olLoLooLLo...
    ..oPpoLLloPpo...
    ..oppPoLooppPo..
    ..oLppoLooLppo..
    ..oLLooLooLLlo..
    ...oPpLLoPpoo...
    ..oLppoLoppLo...
    ..olppPLoppPo...
    ...ooLpLoopo....
    ....oLLLLoLho...
    ....oooLooooo...
    .......oLo......
    .......oLo......
    .......omo......
    ........o.......`],
  strawberry: [SEEDS, SPROUT, `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ....ooo..ooo....
    ...oLhLoolhLo...
    ...olLloolLlo...
    ..oooooLLooooo..
    .oLhLooLLooLhLo.
    .olLlLoLLoLlLlo.
    ..oooooLLooooo..
    .......omo......
    ........o.......`, `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ....ooo..ooo....
    ...oLhLoolhLo...
    ...olLlooyfLo...
    ..oooooLfyfooo..
    .oLhLooLLfooLho.
    .olLlLoLLoLlLlo.
    .oooffoLLooooo..
    .oLhfyfLLoLhLo..
    .olLlfoLLoLlLlo.
    ..oooooLLooooo..
    .......omo......
    ........o.......`, `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ....ooo..ooo....
    ...oLhLoolhLo...
    ...olLlooLlLo...
    ..ooooRLooooo...
    .oLhLRsrRoLhLo..
    .olLlRrrRoLlLlo.
    ..oooRRRLooRoo..
    .oRoooRLoooRsRo.
    oRsrRoLLoLhRrRo.
    oRrrRLLLoLlRRo..
    .oRRoooLLooooo..
    ..oo...omo......
    ........o.......`],
};

export function cropGrids(id) {
  return CROP_ART[id].map((rows) => parse(rows, L));
}
