// Enemy sprites. The nobushi and Jūbei are people, built on the shared character grids; the
// yōkai are hand-drawn grids with a few poses each: rest/move frames, the tell (a wind-up pose that
// reads at a glance), the attack, and a hurt frame. Anchors are at the feet (bottom-centre).
import { parse, grid, set, ellipse, outline } from './raster.js';

export const ENEMY_LOOKS = {
  bandit: {
    hair: ['ink0', 'ink2', 'ink3'], skin: ['skin0', 'skin2', 'skin3', 'skin4'],
    kosode: ['stone0', 'stone1', 'stone2', 'stone3'], hakama: ['wood0', 'wood1', 'wood2', 'wood3'],
    obi: ['ink0', 'ink2'], feet: ['wood1', 'wood3'], collar: ['ink2', 'ink3'], cord: 'red1',
    style: 'band', sword: true,
  },
  jubei: {
    hair: ['ink0', 'ink1', 'ink2'], skin: ['skin1', 'skin2', 'skin3', 'skin4'],
    kosode: ['ink0', 'ink1', 'ink2', 'ink3'], hakama: ['red0', 'red0', 'red1', 'red2'],
    obi: ['gold0', 'gold1'], feet: ['ink1', 'ink4'], collar: ['red1', 'red2'], cord: 'gold2',
    style: 'topknot', sword: true, age: 1, beard: true,
  },
};

// Karakasa-obake: a closed paper umbrella with one eye, a tongue and a single geta.
const KASA = { o: 'ink0', a: 'red1', b: 'red2', c: 'red3', d: 'red4', w: 'ink6', e: 'ink0', t: 'sakura2', s: 'wood2', g: 'wood3', G: 'wood1' };
const KARAKASA = {
  idle0: `
    .......oo.......
    ......oaao......
    .....oabbao.....
    .....oabcbo.....
    ....oabcdcbo....
    ....oabcdcbo....
    ...oabwwwcbao...
    ...oabweecbao...
    ...oabwwwcbao...
    ..oaabcccccbao..
    ..oabbctttcbbo..
    .oaabbcctccbbao.
    .oabbbccccbbbbo.
    oooooooooooooooo
    .......os.......
    .......os.......
    .......os.......
    ......oGgo......
    .....oGggGo.....
    .....oooooo.....`,
  idle1: `
    ................
    .......oo.......
    ......oaao......
    .....oabbao.....
    .....oabcbo.....
    ....oabcdcbo....
    ...oabwwwcbao...
    ...oabweecbao...
    ...oabwwwcbao...
    ..oaabcccccbao..
    ..oabbctttcbbo..
    .oaabbcctccbbao.
    .oabbbccccbbbbo.
    oooooooooooooooo
    .......os.......
    .......os.......
    ......oGgo......
    .....oGggGo.....
    .....oooooo.....
    ................`,
  squat: `
    ................
    ................
    ................
    ................
    .......oo.......
    ......oaao......
    .....oabcbo.....
    ....oabwwwbo....
    ...oabweewcbo...
    ..oaabwwwwcbao..
    .oaabbcttccbbao.
    oaabbbcctcccbbao
    oabbbbccccccbbbo
    oooooooooooooooo
    .......os.......
    ......oGgo......
    .....oGggGo.....
    ....oGgggGGo....
    ....oooooooo....
    ................`,
  leap: `
    .......oo.......
    ......oaao......
    ......oabo......
    .....oabcbo.....
    .....oabcbo.....
    ....oabcdcbo....
    ....oabwwwbo....
    ...oabweewcbo...
    ...oabwwwwcbo...
    ...oabbctccbo...
    ..oaabbtttcbao..
    ..oabbcctccbbo..
    ..oooooooooooo..
    .......os.......
    .......os.......
    .......os.......
    .......os.......
    ......oGgo......
    ......oGgo......
    ......oooo......`,
};

// Bake-danuki: round belly, dark mask, striped tail.
const TANU = { o: 'ink0', a: 'wood1', b: 'wood2', c: 'wood3', d: 'wood4', m: 'ink1', w: 'ink6', e: 'ink0', n: 'ink0', y: 'straw3', Y: 'straw4', l: 'grass3', S: 'skin3' };
const TANUKI = {
  walk0: `
    ....l...........
    ...olo...oo.....
    ..obbo..obbo....
    ..obcbooobcbo...
    ..obccccccccbo..
    .obmmwccwmmcbo..
    .obmewccwemcbo..
    .obcccnnccccbo..
    ..obccccccbbo...
    .oobyYYYYycbbo..
    obcbyYYYYycbcbo.
    obcbyyYYyycbboao
    .obbcyyyycbbboao
    ..obccccccbbo.ao
    ..oboo..oobo..o.
    ..oo......oo....`,
  walk1: `
    ....l...........
    ...olo...oo.....
    ..obbo..obbo....
    ..obcbooobcbo...
    ..obccccccccbo..
    .obmmwccwmmcbo..
    .obmewccwemcbo..
    .obcccnnccccbo..
    ..obccccccbbo...
    .oobyYYYYycbbo..
    obcbyYYYYycbcbo.
    obcbyyYYyycbboa.
    .obbcyyyycbbboao
    ..obccccccbbo.ao
    ...obo..obo...oo
    ...oo....oo.....`,
  drum: `
    ....l...........
    ...olo...oo.....
    ..obbo..obbo....
    ..obcbooobcbo...
    ..obccccccccbo..
    .obmmwccwmmcbo..
    .obmewccwemcbo..
    .obccnnnncccbo..
    .obbccccccbbbo..
    obcbyYYYYYycbbo.
    obSbyYYYYYycSbo.
    obSbyYYYYYycSbao
    .obbyyYYYyycbboa
    ..obcyyyyycbbo.o
    ..oboo...oobo...
    ..oo.......oo...`,
  roll0: `
    ................
    ................
    ................
    .....oooooo.....
    ...oobbccbboo...
    ..obccaaaaccbo..
    .obcaddddddacbo.
    .obcadcccccacbo.
    .obcadcaaacacbo.
    .obcadcccccacbo.
    .obcaddddddacbo.
    ..obccaaaaccbo..
    ...oobbccbboo...
    .....oooooo.....
    ................
    ................`,
  roll1: `
    ................
    ................
    ................
    .....oooooo.....
    ...oobbccbboo...
    ..obccaaaaccbo..
    .obcaddddddacbo.
    .obcadcaaadacbo.
    .obcadcadcdacbo.
    .obcaddaaacacbo.
    .obcaddddddacbo.
    ..obccaaaaccbo..
    ...oobbccbboo...
    .....oooooo.....
    ................
    ................`,
  dizzy: `
    ..y.....y.......
    ...olo..oo..y...
    ..obbo..obbo....
    ..obcbooobcbo...
    ..obccccccccbo..
    .obmmyccwymcbo..
    .obmeyccyemcbo..
    .obccconccccbo..
    ..obccccccbbo...
    .oobyYYYYycbbo..
    obcbyYYYYycbcbo.
    obcbyyYYyycbboao
    .obbcyyyycbbboao
    ..obccccccbbo.ao
    ..oboo..oobo..o.
    ..oo......oo....`,
};

// Kappa: green skin, a shell, a water dish on the head, a beak.
const KAP = { o: 'ink0', a: 'grass0', b: 'grass1', c: 'grass3', d: 'grass4', w: 'water4', W: 'water3', e: 'ink0', E: 'ink6', k: 'gold1', K: 'gold0', s: 'wood2', S: 'wood1', h: 'ink1' };
const KAPPA = {
  walk0: `
    .....oooooo.....
    ....owWWWWwo....
    ...ohhwwwwhho...
    ...ohcccccchho..
    ..occEeccEecco..
    ..occcckkcccco..
    ..obccKkkKcccbo.
    ...obccccccbbo..
    ..oSsSsbccbbdbo.
    .oSsSsSsbccbddo.
    .oSsSsSsSbcbbco.
    .obSsSsSsbccbco.
    ..oSsSsSsbcbbo..
    ..obbbbbbbbbo...
    ..obco...obco...
    .obcco..obcco...
    .ooooo..ooooo...`,
  walk1: `
    .....oooooo.....
    ....owWWWWwo....
    ...ohhwwwwhho...
    ...ohcccccchho..
    ..occEeccEecco..
    ..occcckkcccco..
    ..obccKkkKcccbo.
    ...obccccccbbo..
    ..oSsSsbccbbdbo.
    .oSsSsSsbccbddo.
    .oSsSsSsSbcbbco.
    .obSsSsSsbccbco.
    ..oSsSsSsbcbbo..
    ..obbbbbbbbbo...
    ...obco.obco....
    ...obcco.obcco..
    ...ooooo.ooooo..`,
  lunge: `
    ................
    ..........oooooo
    .........owWWWWw
    ........ohhwwwwh
    ......oohcccccch
    ...oocccEeccEecc
    .oodbcccckkkkkkk
    odddbbccKkkkkkko
    obSsSsbbcccccco.
    oSsSsSsSbbbbbo..
    oSsSsSsSbccbdo..
    .oSsSsSsbcbddo..
    ..obbbbbbbbbo...
    ..obco...obco...
    .obcco..obcco...
    .ooooo..ooooo...`,
  lurk: `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .....oooooo.....
    ....owWWWWwo....
    ...ohhwwwwhho...
    ...ohEeccEehho..
    ..oooooooooooo..
    ................`,
};

// Chōchin-obake: a paper lantern with ribs, one split mouth, and a long tongue.
const CHO = { o: 'ink0', a: 'straw2', b: 'straw3', c: 'straw4', d: 'ink6', r: 'red1', R: 'red2', k: 'ink1', K: 'ink2', e: 'ink0', w: 'ink6', t: 'sakura2', T: 'sakura1', g: 'gold2', G: 'gold3' };
const CHOCHIN = {
  float0: `
    .....okkkko.....
    ....oKKKKKKo....
    ...oaabbbccao...
    ..oaabbbbccdao..
    ..orrrrrrrrrro..
    ..oabbwwbbccao..
    ..oabbweebcdao..
    ..orrrwwrrrrro..
    ..oabbbbbbccao..
    ..oaeeeeeeecao..
    ..orrettttrrro..
    ..oabbbtTbccao..
    ...oabbbtbcao...
    ....oKKKtKKo....
    .....okkTko.....
    ........t.......
    ........T.......`,
  float1: `
    .....okkkko.....
    ....oKKKKKKo....
    ...oaabbbccao...
    ..oaabbbbccdao..
    ..orrrrrrrrrro..
    ..oabbwwbbccao..
    ..oabbweebcdao..
    ..orrrwwrrrrro..
    ..oabbbbbbccao..
    ..oaeeeeeeecao..
    ..orrettttrrro..
    ..oabbbtTbccao..
    ...oabbbtbcao...
    ....oKKKtKKo....
    .....okktko.....
    .......T........
    ......T.........`,
  glow: `
    .....okkkko.....
    ....oKKKKKKo....
    ...oaabbbccao...
    ..oaabbbbccdao..
    ..orrrrrrrrrro..
    ..oabbwwbbccao..
    ..oabbweebcdao..
    ..orrrwwrrrrro..
    ..oagGGGGGgcao..
    ..oaGGGGGGGGao..
    ..orGGGGGGGGro..
    ..oagGGGGGgcao..
    ...oabggggcao...
    ....oKKKKKKo....
    .....okkkko.....
    ................
    ................`,
};

// Yūrei: white burial robe, long black hair over the face, hands held limp, no feet.
const YUR = { o: 'indigo0', a: 'indigo2', b: 'ink5', c: 'ink6', h: 'ink0', H: 'ink1', s: 'indigo3', e: 'red2', t: 'water4' };
const YUREI = {
  drift0: `
    .....oooooo.....
    ....oHHHHHHo....
    ...oHHhhhhHHo...
    ...oHhsshshHo...
    ...oHhsshshHo...
    ...oHhhsshhHo...
    ...oHhhhhhhHo...
    ...oHhoccohhHo..
    ..oHHoccccoHHo..
    ..oHobcccccoHo..
    .oobcccacccbbo..
    obbcccaccccbcbo.
    ossooccaccooss..
    .oo.occaccco.o..
    ....occaccco....
    ....obcaccbo....
    ....obccacbo....
    .....obccbo.....
    .....obcbbo.....
    ......obbo......
    ......obo.......
    .......oo.......
    ........o.......
    ........o.......`,
  drift1: `
    .....oooooo.....
    ....oHHHHHHo....
    ...oHHhhhhHHo...
    ...oHhsshshHo...
    ...oHhsshshHo...
    ...oHhhsshhHo...
    ...oHhhhhhhHo...
    ...oHhoccohhHo..
    ..oHHoccccoHHo..
    ..oHobcccccoHo..
    .oobcccacccbbo..
    obbcccaccccbcbo.
    ossooccaccooss..
    .oo.occaccco.o..
    ....occaccco....
    ....obcaccbo....
    ....obccacbo....
    .....obccbo.....
    .....obcbbo.....
    ......obbo......
    .....obo........
    .....oo.........
    ....o...........
    ................`,
  reach: `
    .....oooooo.....
    ....oHHHHHHo....
    ...oHHhhhhHHo...
    ...oHhehhehHo...
    ...oHhsshshHo...
    ...oHhhsshhHo...
    ...oHhhhhhhHo...
    ..ooHhoccohhHoo.
    .ossoccccccoosso
    ossbcccccccccbso
    oo.bcccaccccb.oo
    ...occcaccccco..
    ...occcacccco...
    ....occaccco....
    ....occaccco....
    ....obcaccbo....
    ....obccacbo....
    .....obccbo.....
    .....obcbbo.....
    ......obbo......
    ......obo.......
    .......oo.......
    ........o.......
    ........o.......`,
};

const SETS = [['karakasa', KARAKASA, KASA], ['tanuki', TANUKI, TANU], ['kappa', KAPPA, KAP], ['chochin', CHOCHIN, CHO], ['yurei', YUREI, YUR]];

/** Every yōkai frame as `${enemy}_${pose}` -> grid, plus hurt frames (flash is done at draw time). */
export function yokaiFrames() {
  const out = {};
  for (const [id, frames, legend] of SETS) for (const [pose, rows] of Object.entries(frames)) out[`${id}_${pose}`] = parse(rows, legend);
  return out;
}

/** A soft ground shadow and the cold wisps that gather before a yūrei appears. */
export function omens() {
  const wisp = [0, 1].map((f) => {
    const g = grid(20, 10);
    for (const [x, y] of [[3, 6], [9, 3], [15, 7], [6, 1], [13, 2]]) { set(g, x + f, y - f, 'water4'); set(g, x + f, y + 1 - f, 'water3'); }
    return g;
  });
  const glint = grid(7, 7);
  for (let i = 0; i < 7; i++) { set(glint, i, 3, 'ink6'); set(glint, 3, i, 'ink6'); }
  set(glint, 3, 3, 'gold3');
  return { wisp0: wisp[0], wisp1: wisp[1], glint: outline(glint, { color: 'gold1' }), boss_shadow: (() => { const g = grid(26, 8); ellipse(g, 13, 4, 12, 3, 'ink0'); return g; })() };
}
