// 16x16 icons for food and medicine sold in the village (teahouse and apothecary).
import { parse } from './raster.js';

export function foodIcons() {
  return {
    tea: parse(`
      ................
      ................
      ......a..a......
      .......a..a.....
      ......a..a......
      ................
      ...oooooooooo...
      ..oggGGGGGGggo..
      ..oWggggggggWo..
      ..oWwwwwwwwwWo..
      ...oWwwwwwwWo...
      ...oWwwwwwwWo...
      ....oWwwwwWo....
      .....oooooo.....
      ....ossssss.....
      ................`, { o: 'stone0', g: 'grass3', G: 'grass4', W: 'stone4', w: 'stone3', a: 'ink5', s: 'ink3' }),
    dango: parse(`
      ..............b.
      ...........oob..
      ..........opPo..
      .........opPPo..
      ........oppPo...
      ......ooooo.....
      .....owWWo......
      ....owWWWo......
      ...oowwWo.......
      ..ogGGoo........
      .ogGGGo.........
      .oggGo..........
      ..ooo...........
      .b..............
      b...............
      ................`, { o: 'wood0', p: 'sakura2', P: 'sakura3', w: 'ink5', W: 'ink6', g: 'grass3', G: 'grass5', b: 'wood3' }),
    onigiri: parse(`
      ................
      .......oo.......
      ......oWWo......
      .....oWWWWo.....
      .....oWWWwo.....
      ....oWWWWWwo....
      ....oWWWWwwo....
      ...oWWWWWWwwo...
      ...oWWnnnnwwo...
      ..oWWWnnnnWwwo..
      ..oWWnnnnnnwwo..
      ..oWWnnnnnnwwo..
      ...oonnnnnnoo...
      .....oooooo.....
      ................
      ................`, { o: 'ink3', W: 'ink6', w: 'ink5', n: 'teal0' }),
    tonic: parse(`
      ................
      ......oooo......
      ......orro......
      .......oo.......
      ......oGgo......
      .....oGggfo.....
      .....oggggo.....
      ......oggo......
      .....oGgggo.....
      ....oGgRRgfo....
      ....oggRRggo....
      ....oggggggo....
      ....ofggggfo....
      .....offffo.....
      ......oooo......
      ................`, { o: 'wood0', r: 'red2', G: 'gold3', g: 'gold1', f: 'gold0', R: 'red3' }),
  };
}
