// 16x16 item icons: tools, seeds, crops and materials. Every item in src/data/items.js has one.
import { grid, set, line, blit, parse, outline, fillRect, ellipse } from './raster.js';

/** A wooden handle from (x0, y0) to (x1, y1): lit stroke with a darker underside. */
function handle(g, x0, y0, x1, y1) {
  line(g, x0, y0, x1, y1, 'wood4');
  line(g, x0 + 1, y0, x1 + 1, y1, 'wood2');
}

const STEEL = { a: 'stone4', b: 'stone3', c: 'stone2', d: 'stone1' };

function tool(headRows, hx, hy, hand = [2, 14, 11, 5]) {
  const g = grid(16, 16);
  handle(g, ...hand);
  blit(g, parse(headRows, STEEL), hx, hy);
  const o = outline(g, { color: 'ink0' });
  return cropTo16(o);
}

// outline() pads by 1px; trim back to 16x16 (our art keeps a 1px margin so nothing is lost).
function cropTo16(g) {
  const out = grid(16, 16);
  for (let y = 0; y < 16; y++) for (let x = 0; x < 16; x++) out.px[y * 16 + x] = g.px[(y + 1) * g.w + x + 1];
  return out;
}

export function toolIcons() {
  return {
    hoe: tool(`
      ..aab
      .abbcd
      abbccd
      .dd...`, 9, 2, [2, 14, 11, 5]),
    axe: tool(`
      .ab..
      abbc.
      abbcd
      abbcd
      .bcd.
      ..d..`, 9, 1, [3, 14, 10, 4]),
    pickaxe: tool(`
      aab.......
      .abbc...bb
      ...bbcccd.
      .....cd...`, 3, 2, [4, 14, 10, 4]),
    sickle: (() => {
      const g = grid(16, 16);
      handle(g, 3, 14, 6, 9);
      const blade = parse(`
        ..aaab...
        .ab..bc..
        ab....cd.
        .......d.
        .......d.
        ......dd.`, STEEL);
      blit(g, blade, 5, 3);
      return cropTo16(outline(g, { color: 'ink0' }));
    })(),
    can: cropTo16(outline(parse(`
      ................
      ................
      .....aaaaa......
      ....a.....a.....
      ....bbbbbbb.....
      ...bccccccdb....
      ...bcddddddb..cc
      ...bccccccdb.cd.
      ...bcccccccbcd..
      ...bccccccddd...
      ...bcccccccb....
      ...bccccccdb....
      ...bbbbbbbbb....
      ................
      ................
      ................`, { a: 'wood2', b: 'wood1', c: 'gold1', d: 'gold0' }), { color: 'ink0' })),
  };
}

// Seed packets: kraft paper with a coloured band and a sketch of the crop.
function packet(band, dot) {
  const g = parse(`
    ................
    ...oooooooooo...
    ...oppppppppo...
    ...obbbbbbbbo...
    ...opppppppPo...
    ...opp....pPo...
    ...op.dddd.Po...
    ...op.dddd.Po...
    ...opp.dd.pPo...
    ...opppppppPo...
    ...oppkkkkpPo...
    ...opppppppPo...
    ...oPPPPPPPPo...
    ...oooooooooo...
    ................
    ................`, { o: 'wood1', p: 'straw3', P: 'straw2', b: band, d: dot, k: 'wood2' });
  return g;
}

const CROP_L = { o: 'grass0', l: 'grass3', L: 'grass4', h: 'grass5', w: 'ink6', W: 'ink5', V: 'ink4',
  r: 'red2', R: 'red1', s: 'red4', y: 'gold2', p: 'grass4', P: 'grass2', d: 'grass1' };

export function itemIcons() {
  return {
    seed_daikon: packet('red2', 'ink6'),
    seed_komatsuna: packet('grass3', 'grass4'),
    seed_soramame: packet('teal1', 'grass5'),
    seed_strawberry: packet('red1', 'red3'),
    daikon: parse(`
      .....o...o......
      ....oho.oLo.....
      ....oLhoLho.....
      ...oLhLoLLo.....
      ....oLLLLo......
      .....oWwwo......
      .....oWwwwo.....
      .....oWwwwo.....
      .....oWwwwo.....
      .....oVWwwo.....
      ......oWwwo.....
      ......oVWwo.....
      .......oVWo.....
      .......oVo......
      ........o.......
      ................`, CROP_L),
    komatsuna: parse(`
      ................
      ...oo....oo.....
      ..oLho..ohLo....
      ..oLhLooLhLo....
      .oLLhLooLhLLo...
      .oLhLLLLLLhLo...
      ..oLLhLLhLLo....
      ..ooLLLLLLoo....
      ...oLLhLLLo.....
      ....oLhLLo......
      ....owwwwo......
      ....oWwwWo......
      .....oWWo.......
      .....oddo.......
      ......oo........
      ................`, CROP_L),
    soramame: parse(`
      ................
      ..........oo....
      .........oLho...
      ........oLhLo...
      .......oLhLLo...
      ......oLhLLPo...
      .....oLhLpPo....
      ....oLhLpPo.....
      ...oLhLpPPo.....
      ..oLhLpPPo......
      ..oLLpPPo.......
      ..oLpPPo........
      ...oPPo.........
      ....oo..........
      ................
      ................`, CROP_L),
    strawberry: parse(`
      ................
      ......o.o.......
      .....oLoLo......
      ....oLhLhLo.....
      ...oorLLLroo....
      ..orsrrrrrRRo...
      ..orsrrrrrrRo...
      ..orrwrrrwrRo...
      ..orrrrrrrrRo...
      ...orrwrrrRo....
      ...orrrrrRRo....
      ....orrrRRo.....
      .....oRRRo......
      ......ooo.......
      ................
      ................`, CROP_L),
    wood: parse(`
      ................
      ................
      ....oooooo......
      ...oddddddo.....
      ..oaabbbbaao....
      ..oabccccbao....
      ..oabcaacbaoooo.
      ..oabccccbaoddo.
      ..oaabbbbaaoabbo
      ...oooooooooaabo
      ...oddddddoooaao
      ..oaabbbbaaooooo
      ..oabcaacbao....
      ..oaabbbbaao....
      ...oooooooo.....
      ................`, { o: 'wood0', d: 'wood2', a: 'wood3', b: 'wood4', c: 'wood5' }),
    stone: parse(`
      ................
      ................
      ................
      .....oooo.......
      ...oohhlloo.....
      ..ohhhlllmmo....
      ..ohhlllmmmdo...
      .ohllmmmmmmdo...
      .olmmmmmmmdddo..
      .olmmmmmmddddo..
      ..ommmmmdddddo..
      ..oddddddddoo...
      ...ooooooooo....
      ................
      ................
      ................`, { o: 'stone0', d: 'stone1', m: 'stone2', l: 'stone3', h: 'stone4' }),
    hay: parse(`
      ................
      ....o.o..o.o....
      ...oho.oho.o....
      ...ohoohoohoo...
      ..ohhoohhoohho..
      ..ohhhhhhhhhho..
      ...ohhhhhhhho...
      ....obbbbbbo....
      ....oBbbbbBo....
      ...ohhhhhhhho...
      ..ohhhlhhhlhho..
      ..ohlhhlhhhlho..
      ..olhlhllhlhlo..
      ...oooooooooo...
      ................
      ................`, { o: 'straw0', h: 'straw3', l: 'straw2', b: 'straw1', B: 'wood1' }),
    bamboo: parse(`
      ................
      ..........oo....
      .........ohlo...
      ........ohlto...
      .......oooooo...
      ......ohlto.....
      .....ohlto......
      ....ohlto.......
      ...oooooo.......
      ...ohlto........
      ..ohlto.........
      .ohlto..........
      .oooo...........
      ................
      ................
      ................`, { o: 'teal0', h: 'grass5', l: 'grass4', t: 'teal1' }),
  };
}

/** Coin icon for money displays (mon: round with a square hole). */
export function coinIcon() {
  const g = grid(9, 9);
  ellipse(g, 4.5, 4.5, 4.5, 4.5, 'gold1');
  ellipse(g, 4, 4, 3.5, 3.5, 'gold2');
  fillRect(g, 3, 3, 3, 3, 'wood1');
  set(g, 2, 2, 'gold3');
  return g;
}
