// 16x16 item icons: tools, seeds, crops and materials. Every item in src/data/items.js has one.
import { grid, set, line, blit, parse, outline, fillRect, ellipse, crop, recolor } from './raster.js';
import { produceIcon, GENERATED_CROPS } from './cropgen.js';

// Seed packet [band, sketch] colours for generated crops.
const SEED_COLORS = {
  satoimo: ['wood2', 'wood4'], rice: ['gold1', 'straw4'], edamame: ['grass3', 'grass5'], nasu: ['sakura0', 'indigo2'],
  kyuri: ['grass2', 'grass4'], kabocha: ['gold0', 'grass2'], suika: ['red2', 'grass4'], shoga: ['straw2', 'sakura2'],
  shiso: ['sakura1', 'grass3'], satsumaimo: ['red1', 'sakura2'], soba: ['ink3', 'ink6'], daizu: ['straw1', 'straw3'],
  azuki: ['red0', 'red2'], kabu: ['sakura2', 'ink6'], gobo: ['wood1', 'wood3'], hakusai: ['grass4', 'ink6'],
  negi: ['teal1', 'ink6'], shungiku: ['gold1', 'grass4'],
};

// Tool-head recolours per tier: basic steel, iron, steel, tamahagane.
const TIER_STEEL = [null,
  { stone4: 'ink5', stone3: 'ink4', stone2: 'ink3', stone1: 'ink2' },
  { stone4: 'water4', stone3: 'ink5', stone2: 'water1', stone1: 'water0' },
  { stone4: 'gold3', stone3: 'sakura3', stone2: 'sakura1', stone1: 'sakura0' },
];

/** Tool icons for tiers 1-3 as { 'hoe@1': grid, ... }. */
export function tierToolIcons() {
  const base = toolIcons();
  const out = {};
  for (let t = 1; t < TIER_STEEL.length; t++) for (const k of ['hoe', 'axe', 'pickaxe']) out[`${k}@${t}`] = recolor(base[k], TIER_STEEL[t]);
  const canTints = [null, { gold1: 'stone3', gold0: 'stone1' }, { gold1: 'water2', gold0: 'water1' }, { gold1: 'gold2', gold0: 'red2' }];
  for (let t = 1; t < 4; t++) out[`can@${t}`] = recolor(base.can, canTints[t]);
  return out;
}

function bar(ramp) {
  const g = grid(16, 16);
  for (const [ox, oy] of [[2, 8], [6, 5]]) {
    for (let y = 0; y < 5; y++) for (let x = 0; x < 9; x++) {
      const edge = x < y * 0.4 || x > 8 - y * 0.4;
      if (!edge) set(g, ox + x, oy + y, y === 0 ? ramp[3] : y < 2 ? ramp[2] : y < 4 ? ramp[1] : ramp[0]);
    }
  }
  return crop(outline(g, { color: null }), 1, 1, 16, 16);
}

function sluiceIcon() {
  const g = grid(16, 16);
  fillRect(g, 3, 3, 3, 11, 'wood2'); fillRect(g, 10, 3, 3, 11, 'wood2');
  line(g, 3, 3, 5, 3, 'wood4'); line(g, 10, 3, 12, 3, 'wood4');
  fillRect(g, 6, 6, 4, 7, 'wood3');
  for (let y = 7; y < 13; y += 2) line(g, 6, y, 9, y, 'wood1');
  fillRect(g, 2, 13, 12, 2, 'water2');
  return crop(outline(g, { color: 'wood0' }), 1, 1, 16, 16);
}

/** A wooden handle from (x0, y0) to (x1, y1): lit stroke with a darker underside. */
function handle(g, x0, y0, x1, y1) {
  line(g, x0, y0, x1, y1, 'wood4');
  line(g, x0 + 1, y0, x1 + 1, y1, 'wood2');
}

const STEEL = { a: 'stone4', b: 'stone3', c: 'stone2', d: 'stone1' };

function tool(headRows, hx, hy, hand = [2, 14, 11, 5]) {
  const g = grid(16, 16);
  handle(g, ...hand);
  blit(g, parse(headRows, STEEL), hx, hy);
  const o = outline(g, { color: 'ink0' });
  return cropTo16(o);
}

// outline() pads by 1px; trim back to 16x16 (our art keeps a 1px margin so nothing is lost).
function cropTo16(g) {
  const out = grid(16, 16);
  for (let y = 0; y < 16; y++) for (let x = 0; x < 16; x++) out.px[y * 16 + x] = g.px[(y + 1) * g.w + x + 1];
  return out;
}

export function toolIcons() {
  return {
    hoe: tool(`
      ..aab
      .abbcd
      abbccd
      .dd...`, 9, 2, [2, 14, 11, 5]),
    axe: tool(`
      .ab..
      abbc.
      abbcd
      abbcd
      .bcd.
      ..d..`, 9, 1, [3, 14, 10, 4]),
    pickaxe: tool(`
      aab.......
      .abbc...bb
      ...bbcccd.
      .....cd...`, 3, 2, [4, 14, 10, 4]),
    sickle: (() => {
      const g = grid(16, 16);
      handle(g, 3, 14, 6, 9);
      const blade = parse(`
        ..aaab...
        .ab..bc..
        ab....cd.
        .......d.
        .......d.
        ......dd.`, STEEL);
      blit(g, blade, 5, 3);
      return cropTo16(outline(g, { color: 'ink0' }));
    })(),
    can: cropTo16(outline(parse(`
      ................
      ................
      .....aaaaa......
      ....a.....a.....
      ....bbbbbbb.....
      ...bccccccdb....
      ...bcddddddb..cc
      ...bccccccdb.cd.
      ...bcccccccbcd..
      ...bccccccddd...
      ...bcccccccb....
      ...bccccccdb....
      ...bbbbbbbbb....
      ................
      ................
      ................`, { a: 'wood2', b: 'wood1', c: 'gold1', d: 'gold0' }), { color: 'ink0' })),
  };
}

// Seed packets: kraft paper with a coloured band and a sketch of the crop.
function packet(band, dot) {
  const g = parse(`
    ................
    ...oooooooooo...
    ...oppppppppo...
    ...obbbbbbbbo...
    ...opppppppPo...
    ...opp....pPo...
    ...op.dddd.Po...
    ...op.dddd.Po...
    ...opp.dd.pPo...
    ...opppppppPo...
    ...oppkkkkpPo...
    ...opppppppPo...
    ...oPPPPPPPPo...
    ...oooooooooo...
    ................
    ................`, { o: 'wood1', p: 'straw3', P: 'straw2', b: band, d: dot, k: 'wood2' });
  return g;
}

const CROP_L = { o: 'grass0', l: 'grass3', L: 'grass4', h: 'grass5', w: 'ink6', W: 'ink5', V: 'ink4',
  r: 'red2', R: 'red1', s: 'red4', y: 'gold2', p: 'grass4', P: 'grass2', d: 'grass1' };

export function itemIcons() {
  return {
    seed_daikon: packet('red2', 'ink6'),
    seed_komatsuna: packet('grass3', 'grass4'),
    seed_soramame: packet('teal1', 'grass5'),
    seed_strawberry: packet('red1', 'red3'),
    ...Object.fromEntries(GENERATED_CROPS.map((id) => [`seed_${id}`, packet(...SEED_COLORS[id])])),
    ...Object.fromEntries(GENERATED_CROPS.map((id) => [id, produceIcon(id)])),
    iron_bar: bar(['ink1', 'ink2', 'ink4', 'ink5']),
    steel_bar: bar(['water0', 'ink3', 'ink5', 'water4']),
    tamahagane: bar(['sakura0', 'sakura1', 'gold2', 'gold3']),
    sluice: sluiceIcon(),
    daikon: parse(`
      .....o...o......
      ....oho.oLo.....
      ....oLhoLho.....
      ...oLhLoLLo.....
      ....oLLLLo......
      .....oWwwo......
      .....oWwwwo.....
      .....oWwwwo.....
      .....oWwwwo.....
      .....oVWwwo.....
      ......oWwwo.....
      ......oVWwo.....
      .......oVWo.....
      .......oVo......
      ........o.......
      ................`, CROP_L),
    komatsuna: parse(`
      ................
      ...oo....oo.....
      ..oLho..ohLo....
      ..oLhLooLhLo....
      .oLLhLooLhLLo...
      .oLhLLLLLLhLo...
      ..oLLhLLhLLo....
      ..ooLLLLLLoo....
      ...oLLhLLLo.....
      ....oLhLLo......
      ....owwwwo......
      ....oWwwWo......
      .....oWWo.......
      .....oddo.......
      ......oo........
      ................`, CROP_L),
    soramame: parse(`
      ................
      ..........oo....
      .........oLho...
      ........oLhLo...
      .......oLhLLo...
      ......oLhLLPo...
      .....oLhLpPo....
      ....oLhLpPo.....
      ...oLhLpPPo.....
      ..oLhLpPPo......
      ..oLLpPPo.......
      ..oLpPPo........
      ...oPPo.........
      ....oo..........
      ................
      ................`, CROP_L),
    strawberry: parse(`
      ................
      ......o.o.......
      .....oLoLo......
      ....oLhLhLo.....
      ...oorLLLroo....
      ..orsrrrrrRRo...
      ..orsrrrrrrRo...
      ..orrwrrrwrRo...
      ..orrrrrrrrRo...
      ...orrwrrrRo....
      ...orrrrrRRo....
      ....orrrRRo.....
      .....oRRRo......
      ......ooo.......
      ................
      ................`, CROP_L),
    wood: parse(`
      ................
      ................
      ....oooooo......
      ...oddddddo.....
      ..oaabbbbaao....
      ..oabccccbao....
      ..oabcaacbaoooo.
      ..oabccccbaoddo.
      ..oaabbbbaaoabbo
      ...oooooooooaabo
      ...oddddddoooaao
      ..oaabbbbaaooooo
      ..oabcaacbao....
      ..oaabbbbaao....
      ...oooooooo.....
      ................`, { o: 'wood0', d: 'wood2', a: 'wood3', b: 'wood4', c: 'wood5' }),
    stone: parse(`
      ................
      ................
      ................
      .....oooo.......
      ...oohhlloo.....
      ..ohhhlllmmo....
      ..ohhlllmmmdo...
      .ohllmmmmmmdo...
      .olmmmmmmmdddo..
      .olmmmmmmddddo..
      ..ommmmmdddddo..
      ..oddddddddoo...
      ...ooooooooo....
      ................
      ................
      ................`, { o: 'stone0', d: 'stone1', m: 'stone2', l: 'stone3', h: 'stone4' }),
    hay: parse(`
      ................
      ....o.o..o.o....
      ...oho.oho.o....
      ...ohoohoohoo...
      ..ohhoohhoohho..
      ..ohhhhhhhhhho..
      ...ohhhhhhhho...
      ....obbbbbbo....
      ....oBbbbbBo....
      ...ohhhhhhhho...
      ..ohhhlhhhlhho..
      ..ohlhhlhhhlho..
      ..olhlhllhlhlo..
      ...oooooooooo...
      ................
      ................`, { o: 'straw0', h: 'straw3', l: 'straw2', b: 'straw1', B: 'wood1' }),
    bamboo: parse(`
      ................
      ..........oo....
      .........ohlo...
      ........ohlto...
      .......oooooo...
      ......ohlto.....
      .....ohlto......
      ....ohlto.......
      ...oooooo.......
      ...ohlto........
      ..ohlto.........
      .ohlto..........
      .oooo...........
      ................
      ................
      ................`, { o: 'teal0', h: 'grass5', l: 'grass4', t: 'teal1' }),
  };
}

/** Coin icon for money displays (mon: round with a square hole). */
export function coinIcon() {
  const g = grid(9, 9);
  ellipse(g, 4.5, 4.5, 4.5, 4.5, 'gold1');
  ellipse(g, 4, 4, 3.5, 3.5, 'gold2');
  fillRect(g, 3, 3, 3, 3, 'wood1');
  set(g, 2, 2, 'gold3');
  return g;
}
