// The spirits of the flooded cellars: the chōchin-obake and the yūrei (their grids), and the
// omens drawn on the ground before a strike (cold wisps, the glint, the boss's shadow).
import { grid, set, ellipse, outline } from './raster.js';

// Chōchin-obake: a paper lantern with ribs, one split mouth, and a long tongue.
export const CHO = { o: 'ink0', a: 'straw2', b: 'straw3', c: 'straw4', d: 'ink6', r: 'red1', R: 'red2', k: 'ink1', K: 'ink2', e: 'ink0', w: 'ink6', t: 'sakura2', T: 'sakura1', g: 'gold2', G: 'gold3' };
export const CHOCHIN = {
  float0: `
    .....okkkko.....
    ....oKKKKKKo....
    ...oaabbbccao...
    ..oaabbbbccdao..
    ..orrrrrrrrrro..
    ..oabbwwbbccao..
    ..oabbweebcdao..
    ..orrrwwrrrrro..
    ..oabbbbbbccao..
    ..oaeeeeeeecao..
    ..orrettttrrro..
    ..oabbbtTbccao..
    ...oabbbtbcao...
    ....oKKKtKKo....
    .....okkTko.....
    ........t.......
    ........T.......`,
  float1: `
    .....okkkko.....
    ....oKKKKKKo....
    ...oaabbbccao...
    ..oaabbbbccdao..
    ..orrrrrrrrrro..
    ..oabbwwbbccao..
    ..oabbweebcdao..
    ..orrrwwrrrrro..
    ..oabbbbbbccao..
    ..oaeeeeeeecao..
    ..orrettttrrro..
    ..oabbbtTbccao..
    ...oabbbtbcao...
    ....oKKKtKKo....
    .....okktko.....
    .......T........
    ......T.........`,
  glow: `
    .....okkkko.....
    ....oKKKKKKo....
    ...oaabbbccao...
    ..oaabbbbccdao..
    ..orrrrrrrrrro..
    ..oabbwwbbccao..
    ..oabbweebcdao..
    ..orrrwwrrrrro..
    ..oagGGGGGgcao..
    ..oaGGGGGGGGao..
    ..orGGGGGGGGro..
    ..oagGGGGGgcao..
    ...oabggggcao...
    ....oKKKKKKo....
    .....okkkko.....
    ................
    ................`,
};

// Yūrei: white burial robe, long black hair over the face, hands held limp, no feet.
export const YUR = { o: 'indigo0', a: 'indigo2', b: 'ink5', c: 'ink6', h: 'ink0', H: 'ink1', s: 'indigo3', e: 'red2', t: 'water4' };
export const YUREI = {
  drift0: `
    .....oooooo.....
    ....oHHHHHHo....
    ...oHHhhhhHHo...
    ...oHhsshshHo...
    ...oHhsshshHo...
    ...oHhhsshhHo...
    ...oHhhhhhhHo...
    ...oHhoccohhHo..
    ..oHHoccccoHHo..
    ..oHobcccccoHo..
    .oobcccacccbbo..
    obbcccaccccbcbo.
    ossooccaccooss..
    .oo.occaccco.o..
    ....occaccco....
    ....obcaccbo....
    ....obccacbo....
    .....obccbo.....
    .....obcbbo.....
    ......obbo......
    ......obo.......
    .......oo.......
    ........o.......
    ........o.......`,
  drift1: `
    .....oooooo.....
    ....oHHHHHHo....
    ...oHHhhhhHHo...
    ...oHhsshshHo...
    ...oHhsshshHo...
    ...oHhhsshhHo...
    ...oHhhhhhhHo...
    ...oHhoccohhHo..
    ..oHHoccccoHHo..
    ..oHobcccccoHo..
    .oobcccacccbbo..
    obbcccaccccbcbo.
    ossooccaccooss..
    .oo.occaccco.o..
    ....occaccco....
    ....obcaccbo....
    ....obccacbo....
    .....obccbo.....
    .....obcbbo.....
    ......obbo......
    .....obo........
    .....oo.........
    ....o...........
    ................`,
  reach: `
    .....oooooo.....
    ....oHHHHHHo....
    ...oHHhhhhHHo...
    ...oHhehhehHo...
    ...oHhsshshHo...
    ...oHhhsshhHo...
    ...oHhhhhhhHo...
    ..ooHhoccohhHoo.
    .ossoccccccoosso
    ossbcccccccccbso
    oo.bcccaccccb.oo
    ...occcaccccco..
    ...occcacccco...
    ....occaccco....
    ....occaccco....
    ....obcaccbo....
    ....obccacbo....
    .....obccbo.....
    .....obcbbo.....
    ......obbo......
    ......obo.......
    .......oo.......
    ........o.......
    ........o.......`,
};

/** A soft ground shadow and the cold wisps that gather before a yūrei appears. */
export function omens() {
  const wisp = [0, 1].map((f) => {
    const g = grid(20, 10);
    for (const [x, y] of [[3, 6], [9, 3], [15, 7], [6, 1], [13, 2]]) { set(g, x + f, y - f, 'water4'); set(g, x + f, y + 1 - f, 'water3'); }
    return g;
  });
  const glint = grid(7, 7);
  for (let i = 0; i < 7; i++) { set(glint, i, 3, 'ink6'); set(glint, 3, i, 'ink6'); }
  set(glint, 3, 3, 'gold3');
  return { wisp0: wisp[0], wisp1: wisp[1], glint: outline(glint, { color: 'gold1' }), boss_shadow: (() => { const g = grid(26, 8); ellipse(g, 13, 4, 12, 3, 'ink0'); return g; })() };
}
