// Tile catalogue shared by the content compiler (for validation) and the renderer.
// `solid` blocks movement. Doors are solid; walking into one triggers its warp or sign.

export const TILES: Record<string, { solid: boolean }> = {
  // outdoor
  roof: { solid: true },
  brick: { solid: true },
  brick_window: { solid: true },
  door: { solid: true },
  bakery_window: { solid: true },
  netto_front: { solid: true },
  sidewalk: { solid: false },
  road: { solid: false },
  road_line: { solid: false },
  grass: { solid: false },
  path: { solid: false },
  flowers: { solid: false },
  tree: { solid: true },
  bench: { solid: true },
  hedge: { solid: true },
  bike_rack: { solid: true },
  bus_sign: { solid: true },
  lamp: { solid: true },
  // indoor
  wall_int: { solid: true },
  window_int: { solid: true },
  floor_stone: { solid: false },
  floor_wood: { solid: false },
  stairs: { solid: false },
  rug: { solid: false },
  door_int: { solid: true },
  door_exit: { solid: true },
  plant: { solid: true },
  mailboxes: { solid: true },
  counter: { solid: true },
  fridge: { solid: true },
  bed_head: { solid: true },
  bed_foot: { solid: true },
  table: { solid: true },
  boxes: { solid: true },
  sofa: { solid: true },
  // shops, city, work, home
  floor_tile: { solid: false },
  carpet: { solid: false },
  cobble: { solid: false },
  rails: { solid: false },
  water: { solid: true },
  shelf: { solid: true },
  cooler: { solid: true },
  pastry_counter: { solid: true },
  register: { solid: true },
  coffee_bar: { solid: true },
  desk: { solid: true },
  bookshelf: { solid: true },
  bar_counter: { solid: true },
  bottles: { solid: true },
  xmas_tree: { solid: true },
  cafe_front: { solid: true },
  pharmacy_front: { solid: true },
  glass_front: { solid: true },
  dokk_front: { solid: true },
  bar_front: { solid: true },
  white_wall: { solid: true },
  white_window: { solid: true },
  fence: { solid: true },
  tram_stop: { solid: true },
  exam_bed: { solid: true },
  dining_table: { solid: true },
};
