#!/usr/bin/env python3
"""Generate the mesh-swap files from assets/export/manifest.json.

    python3 tools/gen_swap_script.py

  src/shared/MeshManifest.luau     manifest the game uses (AssetSwapService)
  tools/studio/SwapGreybox.lua     self-contained Studio command-bar script:
                                   the manifest + src/shared/GreyboxSwap.luau inlined
  KD_fbx_models.zip                what to import in Studio: the module .fbx files,
                                   atlas, SwapGreybox.lua and a README (gitignored)

blender/build_all.py runs this after exporting the meshes.
"""
import json
import shutil
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_JSON = ROOT / "assets" / "export" / "manifest.json"
MANIFEST_LUAU = ROOT / "src" / "shared" / "MeshManifest.luau"
SWAP_MODULE = ROOT / "src" / "shared" / "GreyboxSwap.luau"
SCRIPT = ROOT / "tools" / "studio" / "SwapGreybox.lua"
README = ROOT / "tools" / "studio" / "IMPORT_README.txt"
EXPORT = ROOT / "assets" / "export"
BUNDLE = ROOT / "KD_fbx_models.zip"


def num(v):
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def arr(values):
    return "{ " + ", ".join(num(v) for v in values) + " }"


def rows(manifest, indent):
    out = []
    for key in sorted(manifest):
        e = manifest[key]
        chunks = ", ".join("{ " + ", ".join([str(c["index"])] + [num(v) for v in c["center"] + c["size"]]) + " }" for c in e["chunks"])
        probe = f", p = {arr(e['probe'])}" if "probe" in e else ""
        out.append(f'{indent}["{key}"] = {{ c = {arr(e["center"])}, s = {arr(e["size"])}{probe}, k = {{ {chunks} }} }},')
    return "\n".join(out)


def main():
    manifest = json.loads(MANIFEST_JSON.read_text())
    MANIFEST_LUAU.write_text(
        "-- Generated by tools/gen_swap_script.py from assets/export/manifest.json. Do not edit.\n"
        "-- Local bounds of every exported mesh (studs, module space), read by Shared.GreyboxSwap:\n"
        "-- [key] = { c = centre, s = size, p = probe, k = { { index, cx, cy, cz, sx, sy, sz }, ... } }\n"
        "return {\n" + rows(manifest, "\t") + "\n}\n"
    )
    if shutil.which("stylua"):
        subprocess.run(["stylua", str(MANIFEST_LUAU)], check=True)
    module = SWAP_MODULE.read_text().rstrip("\n")
    body = "\n".join(("\t" + line) if line else "" for line in module.split("\n"))
    SCRIPT.write_text(
        "--[[\n"
        "\tKeep Digging! - snap the imported Blender models onto the map (Studio command bar).\n\n"
        "\t1. Import the .fbx files from KD_fbx_models.zip with the 3D Importer.\n"
        "\t   They can land anywhere; leave them where they appear.\n"
        "\t2. Paste this whole file into the Command Bar and press Enter.\n\n"
        "\tThe Output window says how many stand-ins were placed. Safe to run again;\n"
        "\tCtrl+Z undoes it. Generated by tools/gen_swap_script.py; do not edit.\n"
        "]]\n"
        "local MANIFEST = {\n" + rows(manifest, "\t") + "\n}\n\n"
        "local GreyboxSwap = (function()\n" + body + "\nend)()\n\n"
        "GreyboxSwap.Run({ Manifest = MANIFEST, Undo = true })\n"
    )
    with zipfile.ZipFile(BUNDLE, "w", zipfile.ZIP_DEFLATED) as z:
        for key in sorted(manifest):
            z.write(EXPORT / f"{key}.fbx", f"{key}.fbx")
        z.write(EXPORT / "atlas.png", "atlas.png")
        z.write(SCRIPT, "SwapGreybox.lua")
        z.write(README, "README.txt")
    print(f"wrote {MANIFEST_LUAU.relative_to(ROOT)}, {SCRIPT.relative_to(ROOT)} and {BUNDLE.name} ({len(manifest)} modules)")


if __name__ == "__main__":
    main()
