--[[
	Keep Digging! - snap the imported Blender models onto the map (Studio command bar).

	1. Import the .fbx files from KD_fbx_models.zip with the 3D Importer.
	   They can land anywhere; leave them where they appear.
	2. Paste this whole file into the Command Bar and press Enter.

	The Output window says how many stand-ins were placed. Safe to run again;
	Ctrl+Z undoes it. Generated by tools/gen_swap_script.py; do not edit.
]]
local MANIFEST = {
	["env_artifacts_hall"] = { c = { -161.175, 5.7, 112.095 }, s = { 46.508, 11.4, 52.584 }, p = { -147.223, 7.41, 101.578 }, k = { { 0, -161.175, 5.7, 112.095, 46.508, 11.4, 52.584 } } },
	["env_board_finds"] = { c = { 0, 26.7, 0.9 }, s = { 42, 53.4, 4.4 }, p = { 12.6, 34.71, 0.02 }, k = { { 0, 0, 26.7, 0.9, 42, 53.4, 4.4 } } },
	["env_board_topdiggers"] = { c = { 0, 22.7, 0.9 }, s = { 42, 45.4, 4.4 }, p = { 12.6, 29.51, 0.02 }, k = { { 0, 0, 22.7, 0.9, 42, 45.4, 4.4 } } },
	["env_core"] = { c = { 0, -88, 0 }, s = { 80, 32, 80 }, p = { 24, -83.2, -16 }, k = { { 0, 0, -88, 0, 80, 32, 80 } } },
	["env_distant_hills"] = { c = { 7.5, 26.1, -150.5 }, s = { 725.4, 64.2, 397.4 }, p = { 225.12, 35.73, -229.98 }, k = { { 0, 7.5, 26.1, -150.5, 725.4, 64.2, 397.4 } } },
	["env_fence_ring"] = { c = { 0, 3.812, 0 }, s = { 126.8, 7.625, 126.8 }, p = { 38.04, 4.956, -25.36 }, k = { { 0, 0, 3.812, 0, 126.8, 7.625, 126.8 } } },
	["env_floating_islands"] = { c = { 14, 66.75, -159.8 }, s = { 744.4, 125.5, 568.8 }, p = { 237.32, 85.575, -273.56 }, k = { { 0, 14, 66.75, -159.8, 744.4, 125.5, 568.8 } } },
	["env_gate"] = { c = { 0, 38.55, -145.6 }, s = { 104.4, 77.1, 41.2 }, p = { 31.32, 50.115, -153.84 }, k = { { 0, 0, 38.55, -145.6, 104.4, 77.1, 41.2 } } },
	["env_golden_relic"] = { c = { 168, 2.77, 56 }, s = { 13.223, 5.56, 13.223 }, p = { 171.967, 3.604, 53.355 }, k = { { 0, 168, 2.77, 56, 13.223, 5.56, 13.223 } } },
	["env_grass_bumps"] = { c = { 6, 1, 0 }, s = { 416, 2, 428 }, p = { 130.8, 1.3, -85.6 }, k = { { 0, 6, 1, 0, 416, 2, 428 } } },
	["env_hole_crystal"] = { c = { 0, -48, 0 }, s = { 88, 16, 88 }, p = { 26.4, -45.6, -17.6 }, k = { { 0, 0, -48, 0, 88, 16, 88 }, { 1, 42, -54, 2, 4, 4, 12 } } },
	["env_hole_floor"] = { c = { 0, -70.2, 0 }, s = { 72, 4.4, 72 }, p = { 21.6, -69.54, -14.4 }, k = { { 0, 0, -70.2, 0, 72, 4.4, 72 } } },
	["env_hole_magma"] = { c = { 0, -62, 0 }, s = { 80, 12, 80 }, p = { 24, -60.2, -16 }, k = { { 0, 0, -62, 0, 80, 12, 80 } } },
	["env_hole_ore"] = { c = { 0, -32, 0 }, s = { 104, 16, 104 }, p = { 31.2, -29.6, -20.8 }, k = { { 0, 0, -30, 0, 104, 12, 104 }, { 1, 0, -36, 0, 96, 8, 96 } } },
	["env_hole_stone"] = { c = { 0, -18, 0 }, s = { 120, 12, 120 }, p = { 36, -16.2, -24 }, k = { { 0, 0, -18, 0, 120, 12, 120 }, { 1, 18, -22, 0, 76, 4, 112 } } },
	["env_hole_topsoil"] = { c = { 0, -6, 0 }, s = { 128, 12, 128 }, p = { 38.4, -4.2, -25.6 }, k = { { 0, 0, -4, 0, 128, 8, 128 }, { 1, 0, -8, 0, 128, 8, 128 } } },
	["env_island_body"] = { c = { 4, -26, -8 }, s = { 456, 44, 448 }, p = { 140.8, -19.4, -97.6 }, k = { { 0, 8, -26, -100, 448.001, 44, 264 }, { 1, 4, -26, 124, 456, 44, 184 } } },
	["env_island_top"] = { c = { 4, -2.05, -8 }, s = { 456, 4.1, 448 }, p = { 140.8, -1.435, -97.6 }, k = { { 0, -8, -2, -160, 392, 4, 144 }, { 1, 10, -2, -42, 444, 4, 100 }, { 2, 4, -2.05, 52, 456, 4.1, 96 }, { 3, -8, -2, 156, 424, 4, 120 } } },
	["env_ladder"] = { c = { 29.367, -34.075, -37.588 }, s = { 22.394, 68.15, 27.048 }, p = { 36.085, -23.852, -42.998 }, k = { { 0, 29.367, -34.075, -37.588, 22.394, 68.15, 27.048 } } },
	["env_logo"] = { c = { 27.828, 53.529, -131.6 }, s = { 19.569, 17.834, 1.8 }, p = { 33.698, 56.205, -131.96 }, k = { { 0, 27.828, 53.529, -131.6, 19.569, 17.834, 1.8 } } },
	["env_market_stall"] = { c = { -0.15, 5.45, -0.334 }, s = { 18.9, 10.9, 10.87 }, p = { 5.52, 7.085, -2.508 }, k = { { 0, -0.15, 5.45, -0.334, 18.9, 10.9, 10.87 } } },
	["env_minigame_hub"] = { c = { -0.4, 24.55, 1500 }, s = { 171.2, 65.1, 170.4 }, p = { 50.96, 34.315, 1465.92 }, k = { { 0, -0.4, 24.55, 1500, 171.2, 65.1, 170.4 } } },
	["env_mountains"] = { c = { 0, 220, -1146.5 }, s = { 3200, 560.5, 1265 }, p = { 960, 304.075, -1399.5 }, k = { { 0, -831.75, 150, -1300, 836.5, 420.5, 434 }, { 1, -200, 220, -1500, 900, 560.5, 558 }, { 2, 178, 102.4, -1392, 495, 325.299, 306.9 }, { 3, 572, 170, -1350, 956, 460.5, 496 }, { 4, -1241.5, 120, -700, 717, 360.5, 372 }, { 5, 1241.5, 110, -800, 717, 340.5, 372 } } },
	["env_nature_props"] = { c = { 0.69, 1.919, -0.743 }, s = { 424.653, 4.346, 431.523 }, p = { 128.086, 2.571, -87.047 }, k = { { 0, -0.992, 1.92, -0.743, 421.288, 4.344, 431.523 }, { 1, 5.602, 1.893, -0.371, 414.829, 4.294, 412.052 } } },
	["env_obby_beginner"] = { c = { -148.5, 10.05, -147 }, s = { 115, 20.9, 108 }, p = { -114, 13.185, -168.6 }, k = { { 0, -148.5, 10.05, -147, 115, 20.9, 108 } } },
	["env_obby_pro"] = { c = { 146.441, 27.1, -132.875 }, s = { 94.882, 55, 51.75 }, p = { 174.906, 35.35, -143.225 }, k = { { 0, 146.441, 27.1, -132.875, 94.882, 55, 51.75 } } },
	["env_plaza_lanterns"] = { c = { 1, 3.7, 12 }, s = { 223.8, 7.4, 193.8 }, p = { 68.14, 4.81, -26.76 }, k = { { 0, 1, 3.7, 12, 223.8, 7.4, 193.8 } } },
	["env_portal"] = { c = { 0, 8.616, 1.835 }, s = { 20.859, 17.233, 7.071 }, p = { 6.258, 11.201, 0.421 }, k = { { 0, 0, 8.616, 1.835, 20.859, 17.233, 7.071 } } },
	["env_rim_pebbles"] = { c = { -0.254, 0.3, -0.268 }, s = { 141.282, 0.6, 142.006 }, p = { 42.13, 0.39, -28.67 }, k = { { 0, -0.254, 0.3, -0.268, 141.282, 0.6, 142.006 } } },
	["env_vip_lounge"] = { c = { 0, 9.1, 0 }, s = { 24, 18.2, 16 }, p = { 7.2, 11.83, -3.2 }, k = { { 0, 0, 9.1, 0, 24, 18.2, 16 } } },
	["env_waterfall"] = { c = { -218, 10.7, 22 }, s = { 28.2, 21.4, 32.2 }, p = { -209.54, 13.91, 15.56 }, k = { { 0, -218, 10.7, 22, 28.2, 21.4, 32.2 } } },
	["marker_pedestals"] = { c = { -148, 1.9, 111 }, s = { 37, 3.8, 31 }, p = { -136.9, 2.47, 104.8 }, k = { { 0, -148, 1.9, 111, 37, 3.8, 31 } } },
	["prop_bench"] = { c = { 0, 0.725, 0 }, s = { 5, 1.45, 1.6 }, p = { 1.5, 0.943, -0.32 }, k = { { 0, 0, 0.725, 0, 5, 1.45, 1.6 } } },
	["prop_dig_station"] = { c = { -0.022, 1.8, 0.175 }, s = { 7.745, 3.6, 5.35 }, p = { 2.301, 2.34, -0.895 }, k = { { 0, -0.022, 1.8, 0.175, 7.745, 3.6, 5.35 } } },
	["prop_tree_a"] = { c = { -0.825, 10.863, 0 }, s = { 11.55, 21.725, 9.9 }, p = { 2.64, 14.121, -1.98 }, k = { { 0, -0.825, 10.863, 0, 11.55, 21.725, 9.9 } } },
	["prop_tree_b"] = { c = { 0, 9, 0 }, s = { 12, 18, 11 }, p = { 3.6, 11.7, -2.2 }, k = { { 0, 0, 9, 0, 12, 18, 11 } } },
	["prop_tree_c"] = { c = { 0, 13.25, 0 }, s = { 7, 26.5, 7 }, p = { 2.1, 17.225, -1.4 }, k = { { 0, 0, 13.25, 0, 7, 26.5, 7 } } },
}

local GreyboxSwap = (function()
	--[[
		GreyboxSwap: puts imported Blender meshes onto their GREYBOX stand-ins.

		It never trusts the importer's pivot, unit or axis settings. Every mesh
		module has a manifest entry (Shared.MeshManifest, written by
		blender/build_all.py) holding the local bounds of the whole module, of each
		exported mesh object ("chunk") and the position of a tiny "KD_Probe" cube.
		Comparing those with the imported parts gives the importer's scale and
		quarter-turn rotation, so a copy can be placed with local point q at
		standIn:GetPivot() * q. The rotation is decided by a vote over every
		module, because the importer treats all files the same way.

		  GreyboxSwap.Run({ Manifest = require(Shared.MeshManifest) })

		finds the imported models (ServerStorage.KD_Imported, or anywhere in the
		Workspace, matched by file name), moves them into ServerStorage.KD_Imported
		and gives every stand-in with that AssetKey a "<key>_Mesh" child. The
		stand-in's own parts turn invisible but keep their collisions; parts the
		meshes leave out (KeepsVisible: signs, Neon, Glass, see-through parts) stay
		as they are. Running it again replaces the earlier visuals.

		Used by tools/studio/SwapGreybox.lua (Studio command bar, edit time) and
		AssetSwapService (run time). Keep it free of requires: the command-bar
		script inlines this file.
	]]

	local GreyboxSwap = {}

	GreyboxSwap.Yaws = { 0, 90, 180, 270 }
	-- Mean fit error allowed, as a fraction of the module's diagonal.
	GreyboxSwap.Tolerance = 0.03
	GreyboxSwap.FolderName = "KD_Imported"
	-- Other files from Keep Digging! bundles (tools, finds, old marker exports)
	-- that are tidied out of the Workspace when found at its top level.
	GreyboxSwap.TidyPatterns = { "^env_", "^prop_", "^marker_", "^dig_", "^tool_", "^find_" }

	local VISUAL_ATTR = "KD_Visual"
	local SWAPPED_ATTR = "KD_Swapped"

	local function vec(t): Vector3
		return Vector3.new(t[1], t[2], t[3])
	end

	local function vmin(a: Vector3, b: Vector3): Vector3
		return Vector3.new(math.min(a.X, b.X), math.min(a.Y, b.Y), math.min(a.Z, b.Z))
	end

	local function vmax(a: Vector3, b: Vector3): Vector3
		return Vector3.new(math.max(a.X, b.X), math.max(a.Y, b.Y), math.max(a.Z, b.Z))
	end

	-- Manifest rows are plain arrays so the generated file stays compact:
	--   [key] = { c = centre, s = size, p = probe, k = { { index, cx, cy, cz, sx, sy, sz }, ... } }
	function GreyboxSwap.Decode(manifest)
		local out = {}
		for key, row in manifest do
			local chunks = {}
			for _, k in row.k do
				chunks[k[1]] = { Center = Vector3.new(k[2], k[3], k[4]), Size = Vector3.new(k[5], k[6], k[7]) }
			end
			out[string.lower(key)] = {
				Key = key,
				Center = vec(row.c),
				Size = vec(row.s),
				Probe = row.p and vec(row.p) or nil,
				Chunks = chunks,
				ChunkCount = #row.k,
			}
		end
		return out
	end

	-- "env_gate", "env_gate.fbx", "Env_Gate (2)" -> "env_gate"
	function GreyboxSwap.NormaliseName(name: string): string
		local n = string.lower(name)
		n = string.gsub(n, "%s*%(%d+%)$", "")
		n = string.gsub(n, "%.fbx$", "")
		return n
	end

	-- Chunk index of an imported part: "<key>" or "<key>_0" -> 0, "<key>_3" -> 3.
	local function chunkIndex(key: string, partName: string): number?
		local n = string.lower(partName)
		if n == key then
			return 0
		end
		if string.sub(n, 1, #key + 1) == key .. "_" then
			local index = tonumber(string.sub(n, #key + 2))
			if index and index >= 0 and index == math.floor(index) then
				return index
			end
		end
		return nil
	end

	local function isProbe(part: Instance): boolean
		return string.find(string.lower(part.Name), "kd_probe", 1, true) ~= nil
	end

	-- World-axis bounds of a (possibly rotated) part.
	local function partBounds(part: BasePart): (Vector3, Vector3)
		local cf, half = part.CFrame, part.Size / 2
		local x, y, z = cf.XVector, cf.YVector, cf.ZVector
		local extent = Vector3.new(
			math.abs(x.X) * half.X + math.abs(y.X) * half.Y + math.abs(z.X) * half.Z,
			math.abs(x.Y) * half.X + math.abs(y.Y) * half.Y + math.abs(z.Y) * half.Z,
			math.abs(x.Z) * half.X + math.abs(y.Z) * half.Y + math.abs(z.Z) * half.Z
		)
		return cf.Position - extent, cf.Position + extent
	end

	local function baseParts(root: Instance): { BasePart }
		local parts = {}
		if root:IsA("BasePart") then
			table.insert(parts, root)
		end
		for _, d in root:GetDescendants() do
			if d:IsA("BasePart") then
				table.insert(parts, d)
			end
		end
		return parts
	end

	-- What an imported model looks like now: overall bounds (probe excluded),
	-- the centre of every named chunk and the probe position.
	function GreyboxSwap.Observe(root: Instance, key: string)
		local lo, hi
		local chunks, probe = {}, nil
		for _, part in baseParts(root) do
			if isProbe(part) then
				probe = part.Position
			else
				local a, b = partBounds(part)
				lo = lo and vmin(lo, a) or a
				hi = hi and vmax(hi, b) or b
				local index = chunkIndex(key, part.Name)
				if index ~= nil then
					chunks[index] = part.Position
				end
			end
		end
		if not lo then
			return nil
		end
		return { Center = (lo + hi) / 2, Size = hi - lo, Chunks = chunks, Probe = probe }
	end

	-- Scale and per-rotation fit error of an observed import against its entry.
	-- The importer is assumed to map a local offset v (from the entry's centre) to
	-- scale * R(yaw) * v; errors[yaw] is the mean mismatch over the overall size,
	-- the chunk centres and the probe, relative to the module's diagonal.
	function GreyboxSwap.Fit(entry, seen): (number, { [number]: number })
		local scale = seen.Size.Magnitude / math.max(entry.Size.Magnitude, 1e-6)
		local norm = math.max(entry.Size.Magnitude, 1e-3)
		local errors = {}
		for _, yaw in GreyboxSwap.Yaws do
			local r = CFrame.Angles(0, math.rad(yaw), 0)
			local rotated = r:VectorToWorldSpace(entry.Size)
			local want = Vector3.new(math.abs(rotated.X), math.abs(rotated.Y), math.abs(rotated.Z))
			local total, n = (seen.Size / scale - want).Magnitude / norm, 1
			if entry.ChunkCount > 1 then
				for index, chunk in entry.Chunks do
					local at = seen.Chunks[index]
					if at then
						local expect = r:VectorToWorldSpace(chunk.Center - entry.Center)
						total += ((at - seen.Center) / scale - expect).Magnitude / norm
						n += 1
					end
				end
			end
			if entry.Probe and seen.Probe then
				local expect = r:VectorToWorldSpace(entry.Probe - entry.Center)
				total += ((seen.Probe - seen.Center) / scale - expect).Magnitude / norm
				n += 1
			end
			errors[yaw] = total / n
		end
		return scale, errors
	end

	-- The importer rotates every file the same way, so the rotation is chosen by
	-- summing every module's errors. Returns the yaw and whether the evidence
	-- actually told the candidates apart (symmetric modules cannot).
	function GreyboxSwap.ChooseYaw(fits): (number, boolean)
		local totals = {}
		for _, yaw in GreyboxSwap.Yaws do
			totals[yaw] = 0
		end
		for _, fit in fits do
			for yaw, err in fit.Errors do
				totals[yaw] += math.min(err, 1)
			end
		end
		local best, second
		for _, yaw in GreyboxSwap.Yaws do
			if best == nil or totals[yaw] < totals[best] - 1e-9 then
				second = best
				best = yaw
			elseif second == nil or totals[yaw] < totals[second] then
				second = yaw
			end
		end
		return best, totals[second] - totals[best] > 0.01
	end

	-- Moves (and rescales) a copy of the import so local point q of the module
	-- ends up at target * q.
	function GreyboxSwap.Place(visual: Model, target: CFrame, entry, seen, yaw: number, scale: number)
		visual.PrimaryPart = nil
		visual.WorldPivot = CFrame.new(seen.Center) * CFrame.Angles(0, math.rad(yaw), 0)
		if math.abs(scale - 1) > 1e-4 then
			visual:ScaleTo(visual:GetScale() / scale)
		end
		visual:PivotTo(target * CFrame.new(entry.Center))
	end

	local KEEP_MATERIALS = { Neon = true, Glass = true, ForceField = true }

	-- Stand-in parts the meshes leave out, so they stay visible after a swap.
	-- Must match stays_part in blender/kd/meshkit.py.
	function GreyboxSwap.KeepsVisible(part: BasePart): boolean
		if part:GetAttribute("KeepVisible") == true or part:FindFirstChildOfClass("SurfaceGui") ~= nil then
			return true
		end
		local material = part.Material
		if material and KEEP_MATERIALS[material.Name] then
			return true
		end
		return part.Transparency > 0 and part.Transparency < 0.99
	end

	local function hideStandIn(standIn: Instance)
		for _, part in baseParts(standIn) do
			if not GreyboxSwap.KeepsVisible(part) then
				part.Transparency = 1
			end
		end
	end

	local function asModel(inst: Instance): Model
		if inst:IsA("Model") then
			return inst :: Model
		end
		local model = Instance.new("Model")
		inst.Parent = model
		return model
	end

	local function finishVisual(visual: Model)
		for _, d in visual:GetDescendants() do
			if d:IsA("BasePart") then
				if isProbe(d) then
					d:Destroy()
				else
					d.Anchored = true
					d.CanCollide = false
					d.CanQuery = false
					d.CanTouch = false
					d.Massless = true
				end
			end
		end
	end

	local function count(t): number
		local n = 0
		for _ in t do
			n += 1
		end
		return n
	end

	local function sortedKeys(t): { string }
		local keys = {}
		for k in t do
			table.insert(keys, k)
		end
		table.sort(keys)
		return keys
	end

	-- options:
	--   Manifest      raw manifest table (required)
	--   Templates     { [key] = Instance } extra templates (uploaded assets)
	--   Root          where stand-ins and stray imports live (default workspace)
	--   Storage       where KD_Imported lives (default ServerStorage)
	--   SkipSwapped   leave stand-ins that already have a visual alone
	--   Undo          record one undo step (Studio command bar)
	--   Log           print-like function
	function GreyboxSwap.Run(options)
		options = options or {}
		local manifest = GreyboxSwap.Decode(assert(options.Manifest, "GreyboxSwap.Run needs a Manifest"))
		local root = options.Root or workspace
		local storage = options.Storage or game:GetService("ServerStorage")
		local log = options.Log or print
		local report = {
			Swapped = 0,
			StandIns = 0,
			Templates = 0,
			Moved = 0,
			Removed = 0,
			AlreadySwapped = 0,
			Missing = {},
			Mismatched = {},
			Yaw = 0,
			YawDecided = false,
			Scale = 1,
		}

		local history, recording
		if options.Undo then
			local ok, service = pcall(game.GetService, game, "ChangeHistoryService")
			if ok and service then
				history = service
				local began, id = pcall(service.TryBeginRecording, service, "Keep Digging! mesh swap")
				recording = began and id or nil
			end
		end
		local function commit()
			if history and recording then
				pcall(history.FinishRecording, history, recording, Enum.FinishRecordingOperation.Commit)
			end
		end

		local folder = storage:FindFirstChild(GreyboxSwap.FolderName)

		-- 1. templates: uploaded assets, ServerStorage.KD_Imported, stray imports
		local templates = {}
		for key, inst in options.Templates or {} do
			templates[string.lower(key)] = inst
		end
		if folder then
			for _, inst in folder:GetChildren() do
				local key = GreyboxSwap.NormaliseName(inst.Name)
				if manifest[key] and not templates[key] then
					templates[key] = inst
				end
			end
		end
		local candidates = {}
		for _, d in root:GetDescendants() do
			if
				(d:IsA("Model") or d:IsA("BasePart"))
				and manifest[GreyboxSwap.NormaliseName(d.Name)]
				and d:GetAttribute("AssetKey") == nil
				and d:GetAttribute(VISUAL_ATTR) == nil
			then
				table.insert(candidates, d)
			end
		end
		local function ensureFolder()
			if not folder then
				folder = Instance.new("Folder")
				folder.Name = GreyboxSwap.FolderName
				folder.Parent = storage
			end
			return folder
		end
		local claimed = {}
		for _, d in candidates do
			if d.Parent == nil then
				continue -- went with an import destroyed above
			end
			-- skip parts of stand-ins, of our visuals and of imports already claimed
			local inside = false
			local a = d.Parent
			while a and a ~= root do
				if claimed[a] or a:GetAttribute("AssetKey") ~= nil or a:GetAttribute(VISUAL_ATTR) ~= nil then
					inside = true
					break
				end
				a = a.Parent
			end
			if not inside then
				claimed[d] = true
				local key = GreyboxSwap.NormaliseName(d.Name)
				local besideStandIn = false
				for _, sibling in (d.Parent and d.Parent:GetChildren() or {}) do
					local siblingKey = sibling:GetAttribute("AssetKey")
					if type(siblingKey) == "string" and string.lower(siblingKey) == key then
						besideStandIn = true
						break
					end
				end
				if besideStandIn and templates[key] then
					-- a copy left next to its stand-in by an earlier swap script
					d:Destroy()
					report.Removed += 1
				else
					d.Parent = ensureFolder()
					report.Moved += 1
					if not templates[key] then
						templates[key] = d
					end
				end
			end
		end
		for _, d in root:GetChildren() do
			if (d:IsA("Model") or d:IsA("BasePart")) and d:GetAttribute("AssetKey") == nil then
				local name = GreyboxSwap.NormaliseName(d.Name)
				for _, pattern in GreyboxSwap.TidyPatterns do
					if string.find(name, pattern) then
						d.Parent = ensureFolder()
						report.Moved += 1
						break
					end
				end
			end
		end

		-- 2. measure every template and vote on the importer's rotation
		local fits = {}
		local scales = {}
		for key, template in templates do
			local entry = manifest[key]
			local seen = entry and GreyboxSwap.Observe(template, key)
			if seen then
				local scale, errors = GreyboxSwap.Fit(entry, seen)
				fits[key] = { Seen = seen, Scale = scale, Errors = errors }
				table.insert(scales, scale)
			end
		end
		report.Templates = count(fits)
		if report.Templates == 0 then
			commit()
			log(
				"[KD] No imported Keep Digging! models found. Import the .fbx files first (they can land anywhere in the Workspace)."
			)
			return report
		end
		table.sort(scales)
		report.Scale = scales[math.floor((#scales + 1) / 2)]
		report.Yaw, report.YawDecided = GreyboxSwap.ChooseYaw(fits)

		-- 3. swap every stand-in that has a matching template
		local standIns = {}
		for _, d in root:GetDescendants() do
			if d:IsA("Model") then
				local key = d:GetAttribute("AssetKey")
				if type(key) == "string" and manifest[string.lower(key)] then
					table.insert(standIns, d)
				end
			end
		end
		for _, standIn in standIns do
			local key = string.lower(standIn:GetAttribute("AssetKey"))
			local fit = fits[key]
			report.StandIns += 1
			if not fit then
				report.Missing[key] = true
			elseif fit.Errors[report.Yaw] > GreyboxSwap.Tolerance then
				report.Mismatched[key] = fit.Errors[report.Yaw]
			elseif options.SkipSwapped and standIn:GetAttribute(SWAPPED_ATTR) then
				report.AlreadySwapped += 1
			else
				for _, child in standIn:GetChildren() do
					if child:GetAttribute(VISUAL_ATTR) ~= nil then
						child:Destroy()
					end
				end
				hideStandIn(standIn)
				local visual = asModel(templates[key]:Clone())
				visual.Name = key .. "_Mesh"
				visual:SetAttribute(VISUAL_ATTR, key)
				GreyboxSwap.Place(visual, standIn:GetPivot(), manifest[key], fit.Seen, report.Yaw, fit.Scale)
				finishVisual(visual)
				visual.Parent = standIn
				standIn:SetAttribute(SWAPPED_ATTR, key)
				standIn:RemoveTag("GREYBOX")
				report.Swapped += 1
			end
		end

		commit()

		log(
			string.format(
				"[KD] Placed %d of %d stand-ins using %d imported models (importer turn %d°%s, scale x%.2f).%s%s",
				report.Swapped,
				report.StandIns,
				report.Templates,
				report.Yaw,
				report.YawDecided and "" or ", assumed",
				report.Scale,
				report.AlreadySwapped > 0 and string.format(" %d already had their meshes.", report.AlreadySwapped) or "",
				report.Moved > 0
						and string.format(" Moved %d imports into ServerStorage.%s.", report.Moved, GreyboxSwap.FolderName)
					or ""
			)
		)
		local missing = sortedKeys(report.Missing)
		if #missing > 0 then
			log("[KD] Not imported yet (still grey blocks): " .. table.concat(missing, ", "))
		end
		local mismatched = sortedKeys(report.Mismatched)
		if #mismatched > 0 then
			log(
				"[KD] These imports don't match this place's layout; re-import them from the latest zip: "
					.. table.concat(mismatched, ", ")
			)
		end
		return report
	end

	return GreyboxSwap
end)()

GreyboxSwap.Run({ Manifest = MANIFEST, Undo = true })
