// The Hollow Grove (虚ろの森), 56x44, west of the village: a cedar stand, a bamboo thicket with
// shafts of light, a waterfall into a deep pool, and a stream winding south. Forage grows here in
// every season. Legend (see world/gamemap.js): T trees, . grass, , earth, ~ water, b bridge,
// C cliff, W waterfall, B bamboo thicket, t/s trees.
export default {
  id: 'grove',
  name: 'Hollow Grove',
  jp: '虚ろの森',
  ground: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TT............CCCCCCCCCCCCWWWWCCCCCCCCCCCC............TT',
    'TTt......t....CCCCCCCCCCCCWWWWCCCCCCCCCCCC.B.B.B.B.B.BTT',
    'TT...t......t.CCCCCCCCCCCCWWWWCCCCCCCCCCCCB.B.B.B.B.B.TT',
    'TT......t.....CCCCCCCCCCCCWWWWCCCCCCCCCCCC.B.B.B.B.B.BTT',
    'TT..t......t..CCCCCCCCCCCCWWWWCCCCCCCCCCCCB.B.B.B.B.B.TT',
    'TT.....t............~~~~~~~~~~~~~~~~.......B.B.B.B.B.BTT',
    'TT.t......t........~~~~~~~~~~~~~~~~~~.....B.B.....B.B.TT',
    'TT....t............~~~~~~~~~~~~~~~~~~......B.B...B.B.BTT',
    'TTt......t.........~~~~~~~~~~~~~~~~~~.....B.B.....B.B.TT',
    'TT...t......t......~~~~~~~~~~~~~~~~~~......B.B...B.B.BTT',
    'TT......t.......s...~~~~~~~~~~~~~~~~......B.B.....B.B.TT',
    'TT..t......t...........~~~~~~~~~~..........B.B.B.B.B.BTT',
    'TT.....t.................~~...............B.B.B.B.B.B.TT',
    'TT.t......t.............~~.................B.B.B.B.B.BTT',
    'TT....t................~~.................B.B.B.B.B.B.TT',
    'TTt......t..............~~...............s............TT',
    'TT......................~~............................TT',
    'TT......................~~.........,.,,,..............TT',
    'TT............,,,,,,,,,,bb,,,,,,,,,,,,,,,,,,,.........,,',
    'TT..,,,,,.,,,,,,,,,,,,,,bb,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,',
    'TT..,,,,,,,,,,,,,,,,,,,,bb,,,,,,,,,.....,,,,,,,,,,,,,,,,',
    'TT..,,,,,,,,,,..........~~...................,,,,,,,,,,,',
    'TT........s.............~~............................TT',
    'TT......................~~............................TT',
    'TT......................~~............................TT',
    'TT......................~~............................TT',
    'TT......................~~.......s................t...TT',
    'TT.....................~~.............................TT',
    'TT.....................~~.............t...............TT',
    'TT.............t......~~..............................TT',
    'TT...................~~...............................TT',
    'TT..................~~................................TT',
    'TT.................~~.................................TT',
    'TT......t..........~~.................................TT',
    'TT.................~~.......................t.........TT',
    'TT..................~~................................TT',
    'TT..................~~................................TT',
    'TT...................~~...............................TT',
    'TT..........t.........~~...........t...........t......TT',
    'TT.....................~~.............................TT',
    'TTTTTTTTTTTTTTTTTTTTTTT~~TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTT~~TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
  props: [
    { type: 'jizo', tx: 9, ty: 28 },
    { type: 'sign', tx: 52, ty: 19, text: 'sign_grove' },
    { type: 'toro', tx: 36, ty: 13, light: [0, 6] },
  ],
  // Fishing: right under the falls, the rest of the pool, and the stream.
  waters: [{ rect: [23, 7, 32, 9], kind: 'falls' }, { rect: [17, 7, 38, 13], kind: 'pool' }],
  waterKind: 'stream',
  // Slanting light through the bamboo (tile positions of each shaft's top).
  shafts: [[44, 3], [48, 5], [51, 3], [45, 10], [50, 11]],
  warps: [
    { x: 55, y: 20, w: 1, h: 3, to: 'village', tx: 1, ty: 13, dir: 'right' },
  ],
  spawn: { tx: 53, ty: 21, dir: 'left' },
};
