// Yamabuki Shrine Hill (山吹神社), 40x50: a long stair of stone steps through cedar woods, a chain
// of torii, the gravel precinct with the shrine hall, Tomoe's office, and the sealed rear gate.
export default {
  id: 'shrine',
  name: 'Yamabuki Shrine',
  jp: '山吹神社',
  ground: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTT==TTTTTTTTTTTTTTTTTTT',
    'TT....................................TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,t,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,t,.TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,.TT',
    'TT.,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,.TT',
    'TT.,t,,,,,,,,,,,,,====,,,,,,,,,,,,,t,.TT',
    'TT.,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,.TT',
    'TT................SSSS................TT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...SSSS....TT.TT.TT.TT.TT',
    'TTT.TT.TT.TT.TT...SSSS...TT.TT.TT.TT.TTT',
    'TT.TT.TT.TT.TT....SSSS...T.TT.TT.TT.TTTT',
    'TTTT.TT.TT.TT.T...====....TT.TT.TT.TT.TT',
    'TT................====................TT',
    'TT................====................TT',
  ],
  buildings: [
    { id: 'honden', sprite: 'honden', tx: 16, ty: 8, w: 7, h: 3, door: { tx: 19, ty: 10, to: 'honden' } },
    { id: 'shamusho', sprite: 'b_shamusho', tx: 27, ty: 12, w: 5, h: 2, door: { tx: 29, ty: 13, to: 'shamusho' } },
  ],
  props: [
    { type: 'torii', tx: 19, ty: 45, ox: 8 },
    { type: 'torii', tx: 19, ty: 37, ox: 8 },
    { type: 'torii', tx: 19, ty: 29, ox: 8 },
    { type: 'torii', tx: 19, ty: 21, ox: 8 },
    { type: 'toro', tx: 17, ty: 41, light: [0, 6] },
    { type: 'toro', tx: 22, ty: 41, light: [0, 6] },
    { type: 'toro', tx: 17, ty: 25, light: [0, 6] },
    { type: 'toro', tx: 22, ty: 25, light: [0, 6] },
    { type: 'toro', tx: 16, ty: 12, light: [0, 6] },
    { type: 'toro', tx: 23, ty: 12, light: [0, 6] },
    { type: 'ema', tx: 11, ty: 11 },
    { type: 'sacred', tx: 8, ty: 8, kind: 'pine', v: 1 },
    { type: 'gate', tx: 19, ty: 1, ox: 8, block: [2, 1] },
  ],
  warps: [
    { x: 18, y: 49, w: 4, h: 1, to: 'village', tx: 39, ty: 1, dir: 'down' },
  ],
  spawn: { tx: 19, ty: 47, dir: 'up' },
};
