// Yamabuki Village (山吹村), 80x60. The main street runs east to Hinata Farm and west to the Hollow
// Grove; the shrine stair climbs north past the magistrate's office; a back lane holds the dōjō and
// the rice broker; the road crosses the river on a vermilion bridge to Kaito's paddies and the
// Nakasendō. Legend (see world/gamemap.js): T trees, . grass, = cobbles, , earth, ~ water,
// b bridge, s/t sakura and broadleaf trees, f fence, p flooded paddy, c irrigation channel.
export default {
  id: 'village',
  name: 'Yamabuki Village',
  jp: '山吹村',
  ground: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TT....................................====....................................TT',
    'TT....t.........s..............s......====................................t...TT',
    'TT......................t.............====....................................TT',
    'TT....................................====....................................TT',
    'TT.................................s..====............................s.......TT',
    'TT....................................====....................................TT',
    'TT....................................====..s.................................TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    '================================================================================',
    '================================================================================',
    '================================================================================',
    'TT....................................====....................................TT',
    'TT....................................====....,,,,,,,,,,,,,,,,,,,,,,,.s.......TT',
    'TT..ffffffffffff......................====.s..,,,,,,,,,,,,,,,,,,,,,,,.........TT',
    'TT..f,,,,,,,,,,f...t...........t......====....,,,,,,,,,,,,,,,,,,,,,,,.........TT',
    'TT..f,,,,,,,,,,.......................====....,,,,,,,,,,,,,,,,,,,,,,,......t..TT',
    'TT..f,,,,,,,,,,..........s............====....,,,,,,,,,,,,,,,,,,,,,,,.........TT',
    'TT..f,,,,,,,,,,f......................====....,,,,,,,,,,,,,,,,,,,,,,,.........TT',
    'TT..ffffffffffff..................s...====..s.,,,,,,,,,,,,,,,,,,,,,,,.s.......TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    'TT,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,TT',
    'TT,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    'TT....t.....................t.........====...t....................t...........TT',
    'TT....................................====....................................TT',
    'TT..............s.....................====.................................s..TT',
    'TT....................................====.............s......................TT',
    'TT...............................s....====....................................TT',
    'TT....................................====....................................TT',
    'TT........t...........................====..................t.................TT',
    'TT....................................====....................................TT',
    'TT....................................====....................................TT',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    'TT..cccccccccccccccccccccccccccccccc..====..ccccccccccccccccccc...............TT',
    'TT..cccccccccccccccccccccccccccccccc..====..ccccccccccccccccccc...............TT',
    'TT..cppppppppppppppppppppppppppppppc..====..cpppppppppppppppppc...............TT',
    'TT..cppppppppppppppppppppppppppppppc..====..cpppppppppppppppppc...............TT',
    'TT..cccccccccccccccccccccccccccccccc..====..ccccccccccccccccccc............t..TT',
    'TT..cppppppppppppppppppppppppppppppc..====..cpppppppppppppppppc...............TT',
    'TT..cppppppppppppppppppppppppppppppc..====..cpppppppppppppppppc...............TT',
    'TT..cccccccccccccccccccccccccccccccc..====..ccccccccccccccccccc...............TT',
    'TT....................................====,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.....TT',
    'TT.t..................................====,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.....TT',
    'TT....................s...............====....................................TT',
    'TT....................................====....t...............................TT',
    'TT...............................t....====................s.................s.TT',
    'TT....................................====....................................TT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
  // Townhouses are drawn bottom-centred on their footprint; the door is on the footprint's front row.
  buildings: [
    { id: 'yorozuya', sprite: 'b_yorozuya', tx: 4, ty: 10, w: 7, h: 2, door: { tx: 7, ty: 11, to: 'yorozuya' } },
    { id: 'chaya', sprite: 'b_chaya', tx: 13, ty: 10, w: 7, h: 2, door: { tx: 16, ty: 11, to: 'chaya' } },
    { id: 'kajiya', sprite: 'b_kajiya', tx: 24, ty: 10, w: 7, h: 2, door: { tx: 27, ty: 11, to: 'kajiya' }, lights: [[0, -14]] },
    { id: 'house_n1', sprite: 'b_house2', tx: 32, ty: 10, w: 5, h: 2, door: { tx: 34, ty: 11, say: 'house_private' } },
    { id: 'yakuya', sprite: 'b_yakuya', tx: 46, ty: 10, w: 7, h: 2, door: { tx: 49, ty: 11, to: 'yakuya' } },
    { id: 'heibei', sprite: 'minka', tx: 55, ty: 9, w: 7, h: 3, px: -1, py: -64, door: { tx: 58, ty: 11, to: 'heibei' },
      lights: [[20, 84], [38, 84], [76, 84], [92, 84]] },
    { id: 'house_e1', sprite: 'b_house1', tx: 64, ty: 10, w: 5, h: 2, door: { tx: 66, ty: 11, say: 'house_private' } },
    { id: 'house_e2', sprite: 'b_house2', tx: 71, ty: 10, w: 5, h: 2, door: { tx: 73, ty: 11, say: 'house_private' } },
    { id: 'daikansho', sprite: 'b_daikansho', tx: 44, ty: 3, w: 11, h: 3, door: { tx: 49, ty: 5, say: 'daikansho_locked' } },
    { id: 'house_nw', sprite: 'b_house1', tx: 6, ty: 4, w: 5, h: 2, door: { tx: 8, ty: 5, say: 'house_private' } },
    { id: 'archive', sprite: 'kura', tx: 20, ty: 3, w: 3, h: 3, px: -5, py: -32, door: { tx: 21, ty: 5, say: 'archive_ruin' } },
    { id: 'dojo', sprite: 'b_dojo', tx: 4, ty: 25, w: 9, h: 2, door: { tx: 8, ty: 26, say: 'dojo_closed' } },
    { id: 'house_l1', sprite: 'b_house1', tx: 15, ty: 25, w: 5, h: 2, door: { tx: 17, ty: 26, say: 'house_private' } },
    { id: 'house_l2', sprite: 'b_house2', tx: 23, ty: 25, w: 5, h: 2, door: { tx: 25, ty: 26, say: 'house_private' } },
    { id: 'kuroda', sprite: 'b_kuroda', tx: 46, ty: 25, w: 7, h: 2, door: { tx: 49, ty: 26, say: 'kuroda_closed' } },
    { id: 'house_l3', sprite: 'b_house1', tx: 57, ty: 25, w: 5, h: 2, door: { tx: 59, ty: 26, say: 'house_private' } },
    { id: 'house_l4', sprite: 'b_house2', tx: 66, ty: 25, w: 5, h: 2, door: { tx: 68, ty: 26, say: 'house_private' } },
    { id: 'daigo', sprite: 'b_daigo', tx: 44, ty: 37, w: 5, h: 2, door: { tx: 46, ty: 38, to: 'daigo' } },
    { id: 'kaito', sprite: 'b_kaito', tx: 64, ty: 50, w: 5, h: 2, door: { tx: 66, ty: 51, to: 'kaito' } },
    { id: 'well', sprite: 'well', tx: 64, ty: 18, w: 2, h: 1, px: -2, py: -24, water: true },
  ],
  props: [
    { type: 'notice', tx: 43, ty: 11, ox: 8, block: [2, 1] },
    { type: 'toro', tx: 37, ty: 11, light: [0, 6] },
    { type: 'toro', tx: 42, ty: 11, light: [0, 6] },
    { type: 'jizo', tx: 37, ty: 15 },
    { type: 'jizo', tx: 42, ty: 15 },
    { type: 'bench', tx: 20, ty: 11, ox: 4 },
    { type: 'parasol', tx: 21, ty: 11 },
    { type: 'bales', tx: 45, ty: 26 },
    { type: 'bales', tx: 53, ty: 26 },
    { type: 'toro', tx: 37, ty: 39, light: [0, 6] },
    { type: 'toro', tx: 42, ty: 39, light: [0, 6] },
    { type: 'toro', tx: 47, ty: 16, light: [0, 6] },
    { type: 'toro', tx: 67, ty: 22, light: [0, 6] },
    { type: 'sign', tx: 2, ty: 11, text: 'sign_village_west' },
  ],
  waterKind: 'river',
  warps: [
    { x: 79, y: 12, w: 1, h: 3, to: 'farm', tx: 1, ty: 14, dir: 'right' },
    { x: 38, y: 0, w: 4, h: 1, to: 'shrine', tx: 19, ty: 47, dir: 'up' },
    { x: 0, y: 12, w: 1, h: 3, to: 'grove', tx: 54, ty: 21, dir: 'left' },
  ],
  edges: [
    { tx: 38, ty: 59, w: 4, text: 'edge_nakasendo', textIf: ['restored_nakasendo', 'edge_nakasendo_open'] },
  ],
  spawn: { tx: 77, ty: 13, dir: 'left' },
};
