// Yamabuki Village (山吹村), 64x46. The main street runs east to Hinata Farm and west to the Hollow
// Grove; the shrine stair climbs north; a back lane holds the dōjō and the rice merchant; the road
// crosses the river on a vermilion bridge to the paddies and the Nakasendō.
// Legend (see world/gamemap.js): T trees, . grass, = cobbles, , earth, ~ water, b bridge,
// s/t sakura and broadleaf trees, f fence, p flooded paddy, c irrigation channel.
export default {
  id: 'village',
  name: 'Yamabuki Village',
  jp: '山吹村',
  ground: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TT............................====............................TT',
    'TT..t.........s...........s...====..........................t.TT',
    'TT....................t.......====............................TT',
    'TT............................====............................TT',
    'TT.......s...................s====............................TT',
    'TT............................====.s..........................TT',
    'TT............................====............................TT',
    'TT............................====............................TT',
    'TT............................====............................TT',
    '================================================================',
    '================================================================',
    '================================================================',
    'TT............................====............................TT',
    'TT.ffffffffff.................====...,,,,,,,,,,,,,,,,,,,,.s...TT',
    'TT.f,,,,,,,,f...t.........t...====.s.,,,,,,,,,,,,,,,,,,,,.....TT',
    'TT.f,,,,,,,,..................====...,,,,,,,,,,,,,,,,,,,,...t.TT',
    'TT.f,,,,,,,,f........s........====...,,,,,,,,,,,,,,,,,,,,.....TT',
    'TT.ffffffffff.................====...,,,,,,,,,,,,,,,,,,,,.....TT',
    'TT............................====..s.....................s...TT',
    'TT............................====............................TT',
    'TT............................====............................TT',
    'TT............................====............................TT',
    'TT,,,,,,,,,,,,,,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,,,,,,,,,,,,,,TT',
    'TT,,,,,,,,,,,,,,,,,,,,,,,,,,,,====,,,,,,,,,,,,,,,,,,,,,,,,,,,,TT',
    'TT............................====............................TT',
    'TT............................====..........................t.TT',
    'TT...t..................s.....====....t.......................TT',
    'TT............................====......................s.....TT',
    'TT......t...................t.====............................TT',
    'TT............................====............................TT',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bbbb~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
    'TT..cccccccccccccccccccccccc..====..cccccccccccccccccccccccc..TT',
    'TT..cppppppppppppppppppppppc..====..cppppppppppppppppppppppc..TT',
    'TT..cppppppppppppppppppppppc..====..cppppppppppppppppppppppc..TT',
    'TT..cccccccccccccccccccccccc..====..cccccccccccccccccccccccc..TT',
    'TT..cppppppppppppppppppppppc..====..cppppppppppppppppppppppc..TT',
    'TT..cppppppppppppppppppppppc..====..cppppppppppppppppppppppc..TT',
    'TT..cccccccccccccccccccccccc..====..cccccccccccccccccccccccc..TT',
    'TT............................====............................TT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT====TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
  // Townhouses are drawn bottom-centred on their footprint; the door is on the footprint's front row.
  buildings: [
    { id: 'yorozuya', sprite: 'b_yorozuya', tx: 3, ty: 9, w: 7, h: 2, door: { tx: 6, ty: 10, to: 'yorozuya' } },
    { id: 'chaya', sprite: 'b_chaya', tx: 11, ty: 9, w: 7, h: 2, door: { tx: 14, ty: 10, to: 'chaya' } },
    { id: 'kajiya', sprite: 'b_kajiya', tx: 21, ty: 9, w: 7, h: 2, door: { tx: 24, ty: 10, to: 'kajiya' }, lights: [[0, -14]] },
    { id: 'yakuya', sprite: 'b_yakuya', tx: 38, ty: 9, w: 7, h: 2, door: { tx: 41, ty: 10, to: 'yakuya' } },
    { id: 'heibei', sprite: 'minka', tx: 47, ty: 8, w: 7, h: 3, px: -1, py: -64, door: { tx: 50, ty: 10, to: 'heibei' },
      lights: [[20, 84], [38, 84], [76, 84], [92, 84]] },
    { id: 'house_e', sprite: 'b_house2', tx: 56, ty: 9, w: 5, h: 2, door: { tx: 58, ty: 10, say: 'house_private' } },
    { id: 'daikansho', sprite: 'b_daikansho', tx: 36, ty: 3, w: 11, h: 3, door: { tx: 41, ty: 5, say: 'daikansho_locked' } },
    { id: 'house_nw', sprite: 'b_house1', tx: 5, ty: 4, w: 5, h: 2, door: { tx: 7, ty: 5, say: 'house_private' } },
    { id: 'dojo', sprite: 'b_dojo', tx: 3, ty: 22, w: 9, h: 2, door: { tx: 7, ty: 23, say: 'dojo_closed' } },
    { id: 'house_lane', sprite: 'b_house1', tx: 14, ty: 22, w: 5, h: 2, door: { tx: 16, ty: 23, say: 'house_private' } },
    { id: 'house_lane2', sprite: 'b_house2', tx: 22, ty: 22, w: 5, h: 2, door: { tx: 24, ty: 23, say: 'house_private' } },
    { id: 'kuroda', sprite: 'b_kuroda', tx: 38, ty: 22, w: 7, h: 2, door: { tx: 41, ty: 23, say: 'kuroda_closed' } },
    { id: 'house_se', sprite: 'b_house1', tx: 51, ty: 22, w: 5, h: 2, door: { tx: 53, ty: 23, say: 'house_private' } },
    { id: 'daigo', sprite: 'b_daigo', tx: 12, ty: 28, w: 5, h: 2, door: { tx: 14, ty: 29, to: 'daigo' } },
    { id: 'kaito', sprite: 'b_kaito', tx: 46, ty: 29, w: 5, h: 2, door: { tx: 48, ty: 30, to: 'kaito' } },
    { id: 'well', sprite: 'well', tx: 53, ty: 16, w: 2, h: 1, px: -2, py: -24, water: true },
  ],
  props: [
    { type: 'notice', tx: 35, ty: 10, ox: 8, block: [2, 1] },
    { type: 'toro', tx: 29, ty: 10, light: [0, 6] },
    { type: 'toro', tx: 34, ty: 10, light: [0, 6] },
    { type: 'jizo', tx: 29, ty: 15 },
    { type: 'jizo', tx: 34, ty: 15 },
    { type: 'bench', tx: 18, ty: 10, ox: 4 },
    { type: 'parasol', tx: 19, ty: 10 },
    { type: 'bales', tx: 45, ty: 23 },
    { type: 'bales', tx: 36, ty: 23 },
    { type: 'toro', tx: 29, ty: 31, light: [0, 6] },
    { type: 'toro', tx: 34, ty: 31, light: [0, 6] },
    { type: 'toro', tx: 38, ty: 15, light: [0, 6] },
    { type: 'toro', tx: 55, ty: 19, light: [0, 6] },
    { type: 'sign', tx: 2, ty: 10, text: 'sign_village_west' },
  ],
  warps: [
    { x: 63, y: 11, w: 1, h: 3, to: 'farm', tx: 1, ty: 14, dir: 'right' },
    { x: 30, y: 0, w: 4, h: 1, to: 'shrine', tx: 19, ty: 47, dir: 'up' },
  ],
  edges: [
    { tx: 0, ty: 11, h: 3, text: 'edge_grove' },
    { tx: 30, ty: 45, w: 4, text: 'edge_nakasendo' },
  ],
  spawn: { tx: 61, ty: 12, dir: 'left' },
};
